#!/usr/bin/env bats

# `manifest cleanup` — scope guards for the verb that removes Manifest's own
# leftovers.
#
# The retired `<basename>.manifest` sidecars this command detects were committed
# by accident in 25 of 365 fleet repos (commit 3b94fed, v58.0.0), so the tracked
# case is the common case in the product, not an edge case. Deleting one behind
# the user's back would be TRACKER §3 again: the next ship's bare `git add .`
# would carry the deletion into somebody else's release.
#
# These assert file state (deleted / provably still present), not log lines, per
# the §12b test-policy ratchet.

load 'helpers/setup'

setup() {
    load_modules "core/manifest-config.sh" "docs/manifest-documentation.sh" \
                 "docs/manifest-cleanup-docs.sh" "git/manifest-git.sh" \
                 "system/manifest-runtime-cleanup.sh"
    set_default_configuration
    SCRATCH="$(mk_scratch)"
    cd "$SCRATCH"
    git init -q
    git config user.email "test@example.com"
    git config user.name "Test"
    mkdir -p docs scripts
    echo "1.0.0" > VERSION
    git add VERSION && git commit -q -m "init repo"
    MANIFEST_CLI_PROJECT_ROOT="$SCRATCH"
    export MANIFEST_CLI_PROJECT_ROOT
}

teardown() {
    cd /tmp
    rm -rf "$SCRATCH"
}

# Write all five sidecars the pre-3b94fed write_scaffold_no_clobber could
# produce. Two of them (.env.example.manifest, scripts/run-tests.sh.manifest)
# cannot occur in the canonical checkout, so without seeding them here those
# list entries would never be exercised anywhere.
_seed_all_five() {
    echo stale > .gitignore.manifest
    echo stale > robots.txt.manifest
    echo stale > ai.txt.manifest
    echo stale > .env.example.manifest
    echo '#!/bin/bash' > scripts/run-tests.sh.manifest
    chmod +x scripts/run-tests.sh.manifest
}

# POSITIVE CONTROL. Every "was not deleted" assertion below is meaningless
# unless the sweep provably deletes something in this fixture.
@test "POSITIVE CONTROL: all five retired sidecars are detected and removed" {
    _seed_all_five

    run manifest_cleanup_retired_apply "$SCRATCH"
    [ "$status" -eq 0 ]

    [ ! -f ".gitignore.manifest" ]
    [ ! -f "robots.txt.manifest" ]
    [ ! -f "ai.txt.manifest" ]
    [ ! -f ".env.example.manifest" ]
    [ ! -f "scripts/run-tests.sh.manifest" ]
}

@test "a git-tracked sidecar is never deleted, and the tree stays clean" {
    _seed_all_five
    git add .gitignore.manifest
    git commit -q -m "accidentally committed sidecar"

    run manifest_cleanup_retired_apply "$SCRATCH"
    [ "$status" -eq 0 ]

    # Present, still tracked, and — the part that matters — the working tree has
    # no pending deletion for a later `git add .` to sweep into a release.
    [ -f ".gitignore.manifest" ]
    git ls-files --error-unmatch .gitignore.manifest
    run git status --porcelain
    [ -z "$output" ]

    # The untracked ones still went, so the guard is selective, not a blanket
    # refusal that would make this test vacuous.
    [ ! -f "ai.txt.manifest" ]
}

@test "a staged-but-uncommitted sidecar counts as tracked" {
    _seed_all_five
    git add robots.txt.manifest

    run manifest_cleanup_retired_apply "$SCRATCH"
    [ "$status" -eq 0 ]
    [ -f "robots.txt.manifest" ]
}

@test "live files that merely look like scaffolding are never touched" {
    # .env.example is generated by create_default_env_example and managed by
    # `manifest env`; examples/*.yaml.example are tracked reference docs.
    # Neither is residue of a removed writer, so neither is in scope. Only the
    # `.manifest` sidecar of a file is retired — never the file itself.
    _seed_all_five
    echo live > .env.example
    echo live > .gitignore
    echo live > robots.txt
    mkdir -p examples && echo live > examples/manifest.config.yaml.example

    run manifest_cleanup_retired_apply "$SCRATCH"
    [ "$status" -eq 0 ]

    [ -f ".env.example" ]
    [ -f ".gitignore" ]
    [ -f "robots.txt" ]
    [ -f "examples/manifest.config.yaml.example" ]
}

@test "the retired sweep refuses outright when git cannot say what is tracked" {
    _seed_all_five
    printf 'GARBAGE' > .git/index

    run manifest_cleanup_scan_retired "$SCRATCH"
    [ "$status" -ne 0 ]

    run manifest_cleanup_retired_apply "$SCRATCH"
    [ "$status" -eq 0 ]
    # Nothing adjudicated means nothing deleted — an unreadable index must not
    # read as "nothing is tracked" (§6).
    [ -f ".gitignore.manifest" ]
    [ -f "ai.txt.manifest" ]
}

@test "the retired sweep refuses in a directory that is not a git repo" {
    # Outside $SCRATCH on purpose: a subdirectory of a work tree is still
    # inside that work tree, so a fixture under $SCRATCH would be a git repo
    # and this test would pass for the wrong reason.
    local plain
    plain="$(mk_scratch)"
    echo stale > "$plain/.gitignore.manifest"

    run manifest_cleanup_scan_retired "$plain"
    [ "$status" -ne 0 ]

    run manifest_cleanup_retired_apply "$plain"
    [ "$status" -eq 0 ]
    [ -f "$plain/.gitignore.manifest" ]
    rm -rf "$plain"
}

# An unreadable index makes the PARENT index useless for adjudicating a LINKED
# worktree's files too — they are gitignored in the parent, so they read as
# untracked. Before this guard the sweep listed a live worktree's .DS_Store as
# removable, on every ship.
@test "nothing inside a linked git worktree is swept" {
    git worktree add -q -b wt "$SCRATCH/wt" >/dev/null 2>&1 || skip "git worktree unavailable"
    echo junk > "$SCRATCH/wt/.DS_Store"
    mkdir -p "$SCRATCH/wt/docs" && echo junk > "$SCRATCH/wt/docs/x.tmp"
    # Positive control in the same fixture: the main tree's own .DS_Store must
    # still be swept, or "worktree file survived" would prove nothing.
    echo junk > .DS_Store

    run cleanup_temp_files apply
    [ "$status" -eq 0 ]

    [ -f "$SCRATCH/wt/.DS_Store" ]
    [ -f "$SCRATCH/wt/docs/x.tmp" ]
    [ ! -f ".DS_Store" ]
}

# The empty-directory sweep carries its own `find`, so the exclusion added to
# _manifest_cleanup_find did not reach it. Both directions asserted: a
# placeholder inside a live worktree survives, and a main-tree placeholder is
# still removed — without the second assertion this would pass against a sweep
# that had simply stopped working.
@test "no empty directory inside a linked git worktree is removed" {
    git worktree add -q -b wt "$SCRATCH/wt" >/dev/null 2>&1 || skip "git worktree unavailable"
    mkdir -p "$SCRATCH/wt/output"
    mkdir -p "$SCRATCH/mine/placeholder"

    run cleanup_empty_dirs
    [ "$status" -eq 0 ]

    [ -d "$SCRATCH/wt/output" ]
    [ ! -d "$SCRATCH/mine/placeholder" ]
}

@test "cleanup prunes stale worktree records but never removes a live worktree" {
    git worktree add -q -b wt "$SCRATCH/wt" >/dev/null 2>&1 || skip "git worktree unavailable"
    git worktree add -q -b gone "$SCRATCH/gone" >/dev/null 2>&1 || skip "git worktree unavailable"
    echo "uncommitted" > "$SCRATCH/wt/dirty.txt"
    rm -rf "$SCRATCH/gone"

    run manifest_worktree_stale_count "$SCRATCH"
    [ "$status" -eq 0 ]
    [ "$output" -ge 1 ]

    run manifest_worktree_prune "$SCRATCH"
    [ "$status" -eq 0 ]

    # The stale record is gone; the live worktree and its uncommitted file are
    # untouched. Reclaiming that space needs `--force`, which would destroy the
    # uncommitted file — so cleanup reports it and stops.
    run manifest_worktree_stale_count "$SCRATCH"
    [ "$output" -eq 0 ]
    [ -d "$SCRATCH/wt" ]
    [ -f "$SCRATCH/wt/dirty.txt" ]
}

# META-TEST. The one behaviour that must never be added by accident later.
# Scoped to a COMMAND position: the module names the command in prose so the
# operator knows what to run, and that advice must not make this control fire.
@test "no cleanup code path executes 'git worktree remove' or passes --force" {
    local src="$TEST_REPO_ROOT/modules/git/manifest-git.sh"
    local cleanup_src="$TEST_REPO_ROOT/modules/docs/manifest-cleanup-docs.sh"

    # POSITIVE CONTROL, and not optional. This test's assertions are "grep found
    # nothing", which a nonexistent path satisfies just as well as clean code.
    # It was written against $MANIFEST_CLI_ROOT — a variable that does not
    # exist here — so it grepped /modules/... , got exit 2, and passed while an
    # injected `git worktree remove --force` sat in the source. Prove the files
    # are real and that a known-present string is findable before trusting an
    # absence.
    [ -s "$src" ]
    [ -s "$cleanup_src" ]
    grep -q 'manifest_worktree_prune' "$src"
    grep -q 'manifest_cleanup_dispatch' "$cleanup_src"

    # A command-position invocation: start of line, or after ; && || | ( — as
    # opposed to the same words inside a quoted advice string.
    run grep -nE '(^|[;&|(]|[[:space:]]then|[[:space:]]do)[[:space:]]*git([[:space:]]+-C[[:space:]]+[^[:space:]]+)?[[:space:]]+worktree[[:space:]]+remove' "$src" "$cleanup_src"
    [ "$status" -ne 0 ]

    run grep -nE 'worktree[^\n]*--force|--force[^\n]*worktree' "$src" "$cleanup_src"
    [ "$status" -ne 0 ]
}

@test "the summary renderer maps every action to a verb and rejects unknown ones" {
    run _manifest_execution_summary_verb delete
    [ "$status" -eq 0 ] && [ "$output" = "Would remove" ]
    run _manifest_execution_summary_verb create
    [ "$status" -eq 0 ] && [ "$output" = "Would create" ]
    run _manifest_execution_summary_verb update
    [ "$status" -eq 0 ] && [ "$output" = "Would update" ]
    run _manifest_execution_summary_verb bogus
    [ "$status" -ne 0 ]

    # An unknown action must be an error at the call site too, not a blank verb
    # rendered in front of a user.
    manifest_execution_summary_reset
    run manifest_execution_summary_add bogus "Group" "target"
    [ "$status" -ne 0 ]
}

# FORWARD-COMPATIBILITY. 36 preview strings are pinned as contract text across
# 10 test files. This proves a caller can migrate onto the shared renderer
# without changing one byte of its output — which is what keeps the migration
# from requiring a lockstep rewrite of those pinned strings.
@test "the shared renderer reproduces the pinned uninstall sentence byte-exactly" {
    manifest_execution_summary_reset
    manifest_execution_summary_add delete "installation directory" "$HOME/.manifest-cli"
    manifest_execution_summary_add delete "CLI binary" "$HOME/.local/bin/manifest"

    run manifest_execution_summary_render_sentences "  "
    [ "$status" -eq 0 ]
    [ "${lines[0]}" = "  Would remove installation directory: $HOME/.manifest-cli" ]
    [ "${lines[1]}" = "  Would remove CLI binary: $HOME/.local/bin/manifest" ]
}

@test "manifest_format_bytes is exact at every unit boundary" {
    [ "$(manifest_format_bytes 0)" = "0 B" ]
    [ "$(manifest_format_bytes 1)" = "1 B" ]
    [ "$(manifest_format_bytes 1023)" = "1023 B" ]
    [ "$(manifest_format_bytes 1024)" = "1.0 KB" ]
    [ "$(manifest_format_bytes 1536)" = "1.5 KB" ]
    [ "$(manifest_format_bytes 1048576)" = "1.0 MB" ]
    [ "$(manifest_format_bytes 1073741824)" = "1.0 GB" ]
    # Non-numeric input must not render as an empty unit.
    [ "$(manifest_format_bytes abc)" = "0 B" ]
}

# The two relaxations `cleanup` needs, and the proof they did not loosen the
# release path. Defaulting both to true is the whole reason this is safe.
@test "the apply gate keeps refusing an ambiguous target by default" {
    git checkout -q --detach

    # ship/prep/refresh semantics: unchanged.
    run manifest_repo_scope_target_unambiguous "$SCRATCH"
    [ "$status" -ne 0 ]

    # Relaxing only origin is still not enough for a detached HEAD.
    run manifest_repo_scope_target_unambiguous "$SCRATCH" false
    [ "$status" -ne 0 ]

    # cleanup passes both false: it publishes nothing, so neither a missing
    # origin nor a detached HEAD makes its target ambiguous.
    run manifest_repo_scope_target_unambiguous "$SCRATCH" false false
    [ "$status" -eq 0 ]
}

@test "host-state cleanup never touches config, audit, or the rate-limit ledger" {
    local state="$SCRATCH/state"
    mkdir -p "$state/audit" "$state/gh-rate" "$state/locks"
    echo "config" > "$state/manifest.config.global.yaml"
    echo "event"  > "$state/audit/apply.log"
    echo "epochs" > "$state/gh-rate/mutation-epochs"
    echo "lock"   > "$state/locks/repo.lock"

    # A cache root the sweep IS allowed to touch, to prove it ran at all.
    local cache="$SCRATCH/tmp/manifest-cli"
    mkdir -p "$cache/scratch/yaml"
    echo junk > "$cache/scratch/yaml/old.tmp"
    touch -t 200001010000 "$cache/scratch/yaml/old.tmp"

    manifest_install_paths_cache_dirs() { echo "$cache"; }
    export -f manifest_install_paths_cache_dirs 2>/dev/null || true

    run manifest_runtime_state_apply
    [ "$status" -eq 0 ]

    # POSITIVE CONTROL: it provably swept the cache root.
    [ ! -f "$cache/scratch/yaml/old.tmp" ]

    # And left every piece of real state alone.
    [ -f "$state/manifest.config.global.yaml" ]
    [ -f "$state/audit/apply.log" ]
    [ -f "$state/gh-rate/mutation-epochs" ]
    [ -f "$state/locks/repo.lock" ]
}

@test "host-state cleanup spares files younger than the minimum age" {
    local cache="$SCRATCH/tmp/manifest-cli"
    mkdir -p "$cache/scratch/core"
    echo fresh > "$cache/scratch/core/in-flight.tmp"

    manifest_install_paths_cache_dirs() { echo "$cache"; }
    export -f manifest_install_paths_cache_dirs 2>/dev/null || true

    # A concurrent manifest process may be mid-write to a scratch file.
    MANIFEST_CLI_CLEANUP_STATE_MIN_AGE=3600 run manifest_runtime_state_apply
    [ "$status" -eq 0 ]
    [ -f "$cache/scratch/core/in-flight.tmp" ]
}

@test "the cache containment guard refuses roots outside manifest-cli" {
    run _manifest_runtime_cache_path_is_safe "/"
    [ "$status" -ne 0 ]
    run _manifest_runtime_cache_path_is_safe "$HOME"
    [ "$status" -ne 0 ]
    run _manifest_runtime_cache_path_is_safe "/tmp"
    [ "$status" -ne 0 ]
    run _manifest_runtime_cache_path_is_safe "/tmp/somebody-elses-dir"
    [ "$status" -ne 0 ]
    # POSITIVE CONTROL: a real cache root is accepted, or the four refusals
    # above would pass against a guard that refuses everything.
    run _manifest_runtime_cache_path_is_safe "/tmp/manifest-cli"
    [ "$status" -eq 0 ]
}
