#!/usr/bin/env bats

load 'helpers/setup'

setup() {
    load_modules
    # The fleet-init wrapper lives here; pull it in so we can call the
    # internal helper directly.
    # shellcheck disable=SC1091
    source "$TEST_REPO_ROOT/modules/core/manifest-init.sh"
    # shellcheck disable=SC1091
    source "$TEST_REPO_ROOT/modules/fleet/manifest-fleet-detect.sh"

    SCRATCH="$(mk_scratch)"
    HOME="$SCRATCH-home"
    mkdir -p "$HOME"
    export HOME SCRATCH
    cd "$SCRATCH"
}

teardown() {
    rm -rf "$SCRATCH"
    rm -rf "$SCRATCH-home"
}

# Build a TSV in fleet_start's exact format. Caller passes pairs of
# "select<TAB>name" rows; the SELECT column is whatever the caller wrote.
make_tsv() {
    local hash="$1"
    shift
    {
        echo "# MANIFEST FLEET — Directory Inventory"
        echo "# Root: /tmp/example"
        echo "# Depth: 2"
        echo "# Last scanned: 2026-04-25T00:00:00Z"
        echo "# Generated by: Manifest CLI vtest"
        echo "# Canonical config: manifest.fleet.config.yaml"
        echo "# Toggle the SELECT column (true/false), then run: manifest init fleet"
        echo "# DEFAULT-SELECT-HASH: $hash"
        printf "# SELECT\tNAME\tPATH\tTYPE\tHAS_GIT\tREMOTE_URL\tBRANCH\n"
        local row
        for row in "$@"; do
            local sel="${row%%|*}"
            local name="${row#*|}"
            printf "%s\t%s\t/tmp/%s\trepo\ttrue\t\tmain\n" "$sel" "$name" "$name"
        done
    }
}

run_manifest() {
    run bash -c '
        export MANIFEST_CLI_CORE_MODULES_DIR="$TEST_REPO_ROOT/modules"
        source "$TEST_REPO_ROOT/modules/core/manifest-shared-utils.sh"
        source "$TEST_REPO_ROOT/modules/core/manifest-shared-functions.sh"
        source "$TEST_REPO_ROOT/modules/core/manifest-yaml.sh"
        source "$TEST_REPO_ROOT/modules/fleet/manifest-fleet.sh"
        source "$TEST_REPO_ROOT/modules/core/manifest-init.sh"
        cd "$SCRATCH"
        manifest_init_fleet "$@"
    ' bash "$@"
}

@test "stale-detection: unedited TSV (hash matches) is flagged stale" {
    # Compute the hash that fleet_start would have written for the default
    # selection pattern below (true / false).
    local default_hash
    default_hash="$(printf 'true\nfalse\n' | _manifest_hash_short)"

    make_tsv "$default_hash" "true|alpha" "false|beta" > "$SCRATCH/manifest.fleet.tsv"

    run _fleet_init_tsv_is_stale "$SCRATCH/manifest.fleet.tsv" "$SCRATCH/manifest.fleet.config.yaml"
    [ "$status" -eq 0 ]   # 0 = stale (unedited)
}

@test "stale-detection: edited TSV (one row flipped) is NOT flagged stale" {
    local default_hash
    default_hash="$(printf 'true\nfalse\n' | _manifest_hash_short)"

    # Same default hash, but the data rows have been flipped — user edited.
    make_tsv "$default_hash" "false|alpha" "true|beta" > "$SCRATCH/manifest.fleet.tsv"

    run _fleet_init_tsv_is_stale "$SCRATCH/manifest.fleet.tsv" "$SCRATCH/manifest.fleet.config.yaml"
    [ "$status" -eq 1 ]   # 1 = edited
}

@test "stale-detection: TSV without DEFAULT-SELECT-HASH header is NOT flagged stale" {
    # Old-format TSV (no fingerprint header).
    {
        echo "# MANIFEST FLEET — Directory Inventory"
        echo "# Root: /tmp | Depth: 2 | Date: 2026-04-25T00:00:00Z"
        printf "# SELECT\tNAME\tPATH\tTYPE\tHAS_GIT\tREMOTE_URL\tBRANCH\tVERSION\n"
        printf "true\talpha\t/tmp/alpha\trepo\ttrue\t\tmain\t0.0.0\n"
    } > "$SCRATCH/manifest.fleet.tsv"

    run _fleet_init_tsv_is_stale "$SCRATCH/manifest.fleet.tsv" "$SCRATCH/manifest.fleet.config.yaml"
    [ "$status" -eq 1 ]   # not flagged — back-compat with pre-#15 TSVs
}

@test "stale-detection: existing fleet config short-circuits to 'not stale'" {
    local default_hash
    default_hash="$(printf 'true\n' | _manifest_hash_short)"

    make_tsv "$default_hash" "true|alpha" > "$SCRATCH/manifest.fleet.tsv"
    : > "$SCRATCH/manifest.fleet.config.yaml"

    run _fleet_init_tsv_is_stale "$SCRATCH/manifest.fleet.tsv" "$SCRATCH/manifest.fleet.config.yaml"
    [ "$status" -eq 1 ]
}

@test "init fleet phase 1 defaults to compact repo-depth TSV" {
    mkdir -p "$SCRATCH/apps/web/src" "$SCRATCH/services/api/internal"

    run_manifest

    [ "$status" -eq 0 ]
    [ -f "$SCRATCH/manifest.fleet.tsv" ]
    grep -q $'\tapps/web\t' "$SCRATCH/manifest.fleet.tsv"
    grep -q $'\tservices/api\t' "$SCRATCH/manifest.fleet.tsv"
    ! grep -q $'\tapps\t' "$SCRATCH/manifest.fleet.tsv"
    ! grep -q $'\tapps/web/src\t' "$SCRATCH/manifest.fleet.tsv"
    [[ "$output" == *"Inventory mode: repo-depth prompts"* ]]
    [[ "$output" == *"Listed in TSV:"*"2"* ]]
}

@test "init fleet phase 1 TSV uses freshness metadata instead of VERSION column" {
    mkdir -p "$SCRATCH/apps/web"

    run_manifest

    [ "$status" -eq 0 ]
    grep -q '^# Last scanned: ' "$SCRATCH/manifest.fleet.tsv"
    grep -q '^# Generated by: Manifest CLI' "$SCRATCH/manifest.fleet.tsv"
    grep -q '^# Canonical config: manifest.fleet.config.yaml$' "$SCRATCH/manifest.fleet.tsv"
    grep -q $'^# SELECT\tNAME\tPATH\tTYPE\tHAS_GIT\tREMOTE_URL\tBRANCH$' "$SCRATCH/manifest.fleet.tsv"
    ! grep -q $'^# SELECT\tNAME\tPATH\tTYPE\tHAS_GIT\tREMOTE_URL\tBRANCH\tVERSION$' "$SCRATCH/manifest.fleet.tsv"
}

@test "merge_start_tsv preserves selected root workspace row" {
    cat > "$SCRATCH/manifest.fleet.tsv" <<'TSV'
true	rootworkspace	.	infrastructure	true	git@example.com:org/root.git	main
TSV
    local discovered
    discovered="$(printf "svc\tservices/api\tservice\tmain\t1.0.0\tgit@example.com:org/api.git\tfalse\ttrue\ttrue\n")"

    merge_start_tsv "$discovered" "$SCRATCH/manifest.fleet.tsv" "$SCRATCH" 5 > "$SCRATCH/merged.tsv" 2>/dev/null

    grep -q $'^true\trootworkspace\t.\tinfrastructure\ttrue\tgit@example.com:org/root.git\tmain$' "$SCRATCH/merged.tsv"
    grep -q $'^true\tsvc\tservices/api\tservice\ttrue\tgit@example.com:org/api.git\tmain$' "$SCRATCH/merged.tsv"
}

@test "merge_start_tsv keeps empty TSV fields aligned" {
    : > "$SCRATCH/manifest.fleet.tsv"
    local discovered
    discovered="$(printf "plain\tservices/plain\tservice\t\t0.0.0\t\tfalse\tfalse\tfalse\n")"

    merge_start_tsv "$discovered" "$SCRATCH/manifest.fleet.tsv" "$SCRATCH" 5 > "$SCRATCH/merged.tsv" 2>/dev/null

    [ "$(awk -F '\t' '$2 == "plain" {print $5 "|" $6 "|" $7}' "$SCRATCH/merged.tsv")" = "false||" ]
}

@test "init fleet --all-folders writes exhaustive TSV" {
    mkdir -p "$SCRATCH/apps/web/src"

    run_manifest --all-folders --depth 3

    [ "$status" -eq 0 ]
    [ -f "$SCRATCH/manifest.fleet.tsv" ]
    grep -q $'\tapps\t' "$SCRATCH/manifest.fleet.tsv"
    grep -q $'\tapps/web\t' "$SCRATCH/manifest.fleet.tsv"
    grep -q $'\tapps/web/src\t' "$SCRATCH/manifest.fleet.tsv"
    [[ "$output" == *"Inventory mode: all scanned folders"* ]]
}

@test "stale-detection: missing TSV returns not-stale" {
    run _fleet_init_tsv_is_stale "$SCRATCH/does-not-exist.tsv" "$SCRATCH/manifest.fleet.config.yaml"
    [ "$status" -eq 1 ]
}

@test "_manifest_hash_short produces stable output" {
    local h1 h2
    h1="$(printf 'hello\n' | _manifest_hash_short)"
    h2="$(printf 'hello\n' | _manifest_hash_short)"
    [ -n "$h1" ]
    [ "$h1" = "$h2" ]

    # Different input -> different hash.
    local h3
    h3="$(printf 'world\n' | _manifest_hash_short)"
    [ "$h1" != "$h3" ]
}
