#!/usr/bin/env bats

load 'helpers/setup'

setup() {
    load_modules "core/manifest-config.sh" "docs/manifest-documentation.sh"
    set_default_configuration
    SCRATCH="$(mk_scratch)"
    cd "$SCRATCH"
    MANIFEST_CLI_PROJECT_ROOT="$SCRATCH"
    export MANIFEST_CLI_PROJECT_ROOT
}

teardown() {
    cd /tmp
    rm -rf "$SCRATCH"
    unset MANIFEST_CLI_DOCS_RETAIN
}

# Write a changes_file shaped like analyze_changes output so the prepend
# helper has a body to extract.
seed_changes_file() {
    local file="$1"
    local version="$2"
    local body="${3:-### Summary
- Notable changes: 1

### Documentation
- Add fleet adoption planning}"

    cat > "$file" <<EOF
## Highlights for v${version}

${body}
EOF
}

# -----------------------------------------------------------------------------
# _manifest_build_changelog_entry
# -----------------------------------------------------------------------------

@test "build entry: extracts body, formats Keep-a-Changelog header" {
    local changes="${SCRATCH}/changes.md"
    seed_changes_file "$changes" "46.13.6"

    run _manifest_build_changelog_entry "46.13.6" "2026-05-05 12:00:00 UTC" "patch" "$changes"
    [ "$status" -eq 0 ]
    echo "$output" | head -1 | grep -qE '^## \[46\.13\.6\] - 2026-05-05$'
    echo "$output" | grep -q '^\*\*Release Type:\*\* Patch$'
    echo "$output" | grep -q '^### Summary$'
    echo "$output" | grep -q '^- Notable changes: 1$'
    echo "$output" | grep -q '^### Documentation$'
    # No leftover scaffolding from analyze_changes header.
    ! echo "$output" | grep -q '^## Highlights for v'
}

@test "build entry: empty changes file → release-type line carries the no-changes suffix" {
    local empty="${SCRATCH}/empty.md"
    : > "$empty"

    run _manifest_build_changelog_entry "1.0.0" "2026-05-05 12:00:00 UTC" "minor" "$empty"
    [ "$status" -eq 0 ]
    echo "$output" | grep -qE '^## \[1\.0\.0\] - 2026-05-05$'
    echo "$output" | grep -qx '^\*\*Release Type:\*\* Minor — no user-facing changes\.$'
    # No filler Summary section, no leftover narrative paragraph.
    ! echo "$output" | grep -q '^### '
    ! echo "$output" | grep -q "No notable user-facing changes were detected"
}

# -----------------------------------------------------------------------------
# prepend_root_changelog_entry
# -----------------------------------------------------------------------------

@test "prepend: creates root CHANGELOG.md with header on first ship" {
    local changes="${SCRATCH}/changes.md"
    seed_changes_file "$changes" "46.13.6"

    run prepend_root_changelog_entry "$SCRATCH" "46.13.6" "2026-05-05 12:00:00 UTC" "patch" "$changes"
    [ "$status" -eq 0 ]
    [ -f "${SCRATCH}/CHANGELOG.md" ]
    head -1 "${SCRATCH}/CHANGELOG.md" | grep -qx '^# Changelog$'
    grep -q '^## \[46\.13\.6\]' "${SCRATCH}/CHANGELOG.md"
}

@test "prepend: subsequent ships add new entry above existing ones" {
    local changes="${SCRATCH}/changes.md"
    seed_changes_file "$changes" "46.13.6"
    prepend_root_changelog_entry "$SCRATCH" "46.13.6" "2026-05-05 12:00:00 UTC" "patch" "$changes"

    seed_changes_file "$changes" "46.13.7"
    prepend_root_changelog_entry "$SCRATCH" "46.13.7" "2026-05-06 12:00:00 UTC" "patch" "$changes"

    grep -q '^## \[46\.13\.6\]' "${SCRATCH}/CHANGELOG.md"
    grep -q '^## \[46\.13\.7\]' "${SCRATCH}/CHANGELOG.md"
    local p_new p_old
    p_new=$(grep -n '^## \[46\.13\.7\]' "${SCRATCH}/CHANGELOG.md" | cut -d: -f1)
    p_old=$(grep -n '^## \[46\.13\.6\]' "${SCRATCH}/CHANGELOG.md" | cut -d: -f1)
    [ "$p_new" -lt "$p_old" ]
    # Single # Changelog header (no duplication).
    [ "$(grep -c '^# Changelog$' "${SCRATCH}/CHANGELOG.md")" -eq 1 ]
}

@test "prepend: re-shipping the same version replaces the existing entry, not duplicates" {
    local changes="${SCRATCH}/changes.md"
    seed_changes_file "$changes" "46.13.6" "### Summary
- First take"
    prepend_root_changelog_entry "$SCRATCH" "46.13.6" "2026-05-05 12:00:00 UTC" "patch" "$changes"

    seed_changes_file "$changes" "46.13.6" "### Summary
- Updated body"
    prepend_root_changelog_entry "$SCRATCH" "46.13.6" "2026-05-05 12:00:00 UTC" "patch" "$changes"

    [ "$(grep -c '^## \[46\.13\.6\]' "${SCRATCH}/CHANGELOG.md")" -eq 1 ]
    grep -q "Updated body" "${SCRATCH}/CHANGELOG.md"
    ! grep -q "First take" "${SCRATCH}/CHANGELOG.md"
}

@test "docs index: inline version and updated metadata are both refreshed" {
    mkdir -p "${SCRATCH}/docs"
    cat > "${SCRATCH}/docs/INDEX.md" <<'EOF'
# Manifest CLI Documentation

**Version:** 1.0.0 | **Updated:** 2026-05-08
EOF
    manifest_is_canonical_repo() { return 0; }

    run generate_docs_index "1.2.3"

    [ "$status" -eq 0 ]
    grep -qxF "**Version:** 1.2.3 | **Updated:** $(date -u '+%Y-%m-%d')" "${SCRATCH}/docs/INDEX.md"
}

@test "prepend: legacy auto-generated content is replaced, not preserved" {
    cat > "${SCRATCH}/CHANGELOG.md" <<'EOF'
# Old Auto-Generated Changelog

Generated by Manifest CLI v45.0.0
EOF
    local changes="${SCRATCH}/changes.md"
    seed_changes_file "$changes" "46.13.6"

    prepend_root_changelog_entry "$SCRATCH" "46.13.6" "2026-05-05 12:00:00 UTC" "patch" "$changes"

    ! grep -q "Generated by Manifest CLI v45.0.0" "${SCRATCH}/CHANGELOG.md"
    head -1 "${SCRATCH}/CHANGELOG.md" | grep -qx '^# Changelog$'
    grep -q '^## \[46\.13\.6\]' "${SCRATCH}/CHANGELOG.md"
}

@test "prepend: hand-crafted root content is preserved unchanged" {
    cat > "${SCRATCH}/CHANGELOG.md" <<'EOF'
# Changelog

## [45.0.0] - 2026-01-01

**Release Type:** Major

### Notes
Hand-crafted entry.
EOF
    local changes="${SCRATCH}/changes.md"
    seed_changes_file "$changes" "46.13.6"

    prepend_root_changelog_entry "$SCRATCH" "46.13.6" "2026-05-05 12:00:00 UTC" "patch" "$changes"

    grep -q "Hand-crafted entry" "${SCRATCH}/CHANGELOG.md"
    grep -q '^## \[45\.0\.0\]' "${SCRATCH}/CHANGELOG.md"
    grep -q '^## \[46\.13\.6\]' "${SCRATCH}/CHANGELOG.md"
}

# -----------------------------------------------------------------------------
# _manifest_prune_root_changelog
# -----------------------------------------------------------------------------

@test "prune: 'N versions' keeps top N sections, drops older" {
    local changes="${SCRATCH}/changes.md"
    local v
    for v in 1.0.0 2.0.0 3.0.0 4.0.0 5.0.0; do
        seed_changes_file "$changes" "$v"
        prepend_root_changelog_entry "$SCRATCH" "$v" "2026-05-0${v%%.*} 12:00:00 UTC" "minor" "$changes"
    done

    # Now apply 3-version retention.
    _manifest_prune_root_changelog "${SCRATCH}/CHANGELOG.md" "3 versions"

    grep -q '^## \[5\.0\.0\]' "${SCRATCH}/CHANGELOG.md"
    grep -q '^## \[4\.0\.0\]' "${SCRATCH}/CHANGELOG.md"
    grep -q '^## \[3\.0\.0\]' "${SCRATCH}/CHANGELOG.md"
    ! grep -q '^## \[2\.0\.0\]' "${SCRATCH}/CHANGELOG.md"
    ! grep -q '^## \[1\.0\.0\]' "${SCRATCH}/CHANGELOG.md"
}

@test "prune: 'off' keeps every entry" {
    local changes="${SCRATCH}/changes.md"
    local v
    for v in 1.0.0 2.0.0 3.0.0; do
        seed_changes_file "$changes" "$v"
        prepend_root_changelog_entry "$SCRATCH" "$v" "2026-05-0${v%%.*} 12:00:00 UTC" "minor" "$changes"
    done

    _manifest_prune_root_changelog "${SCRATCH}/CHANGELOG.md" "off"

    grep -q '^## \[1\.0\.0\]' "${SCRATCH}/CHANGELOG.md"
    grep -q '^## \[2\.0\.0\]' "${SCRATCH}/CHANGELOG.md"
    grep -q '^## \[3\.0\.0\]' "${SCRATCH}/CHANGELOG.md"
}

@test "prune: 'N days' keeps entries newer than cutoff" {
    # Build a CHANGELOG.md by hand with explicit dates so we can reason
    # about the cutoff without depending on prepend timestamps.
    cat > "${SCRATCH}/CHANGELOG.md" <<EOF
# Changelog

## [3.0.0] - $(date -u '+%Y-%m-%d')

**Release Type:** Minor

Recent.

## [2.0.0] - 2026-04-01

**Release Type:** Minor

Mid.

## [1.0.0] - 2025-01-01

**Release Type:** Major

Old.
EOF

    _manifest_prune_root_changelog "${SCRATCH}/CHANGELOG.md" "30 days"

    grep -q '^## \[3\.0\.0\]' "${SCRATCH}/CHANGELOG.md"
    ! grep -q '^## \[2\.0\.0\]' "${SCRATCH}/CHANGELOG.md"
    ! grep -q '^## \[1\.0\.0\]' "${SCRATCH}/CHANGELOG.md"
}

@test "prune: malformed retain spec leaves file untouched" {
    local changes="${SCRATCH}/changes.md"
    seed_changes_file "$changes" "1.0.0"
    prepend_root_changelog_entry "$SCRATCH" "1.0.0" "2026-05-05 12:00:00 UTC" "minor" "$changes"

    local before
    before="$(cat "${SCRATCH}/CHANGELOG.md")"

    run _manifest_prune_root_changelog "${SCRATCH}/CHANGELOG.md" "banana"
    [ "$status" -eq 0 ]
    [ "$(cat "${SCRATCH}/CHANGELOG.md")" = "$before" ]
}

# -----------------------------------------------------------------------------
# _manifest_parse_retention (moved from cleanup-docs)
# -----------------------------------------------------------------------------

@test "parse retention: '10 versions' → versions / 10" {
    local k v
    _manifest_parse_retention "10 versions" k v
    [ "$k" = "versions" ]
    [ "$v" = "10" ]
}

@test "parse retention: '30 days' → days / 30" {
    local k v
    _manifest_parse_retention "30 days" k v
    [ "$k" = "days" ]
    [ "$v" = "30" ]
}

@test "parse retention: 'off' / empty → off" {
    local k v
    _manifest_parse_retention "off" k v
    [ "$k" = "off" ]
    _manifest_parse_retention "" k v
    [ "$k" = "off" ]
}

@test "parse retention: malformed input returns 1" {
    local k v
    run _manifest_parse_retention "ten versions" k v
    [ "$status" -ne 0 ]
    run _manifest_parse_retention "5 weeks" k v
    [ "$status" -ne 0 ]
}
