#!/usr/bin/env bats

load 'helpers/setup'

setup() {
    load_modules "core/manifest-config.sh" "docs/manifest-documentation.sh"
    set_default_configuration
    SCRATCH="$(mk_scratch)"
    cd "$SCRATCH"
    PROJECT_ROOT="$SCRATCH"
    export PROJECT_ROOT
    mkdir -p docs/zArchive
}

teardown() {
    cd /tmp
    rm -rf "$SCRATCH"
    unset MANIFEST_CLI_DOCS_FOLDER MANIFEST_CLI_DOCS_ARCHIVE_FOLDER
}

# Generate a fake auto-generated CHANGELOG_v<X>.md at $1 with $2 release type
# and $3 body lines (header text follows the pipeline's actual output).
seed_auto_changelog() {
    local file="$1"
    local rtype="${2:-patch}"
    local body="${3:-### Summary
No notable user-facing changes were detected since the previous release tag.}"
    local version date
    version="$(basename "$file" .md | sed 's/^CHANGELOG_v//')"
    date="$(date +%Y-%m-%d)"

    cat > "$file" <<EOF
# Changelog v${version}

**Release Date:** ${date} 12:00:00 UTC
**Release Type:** ${rtype}

## Highlights for v${version}

${body}

---
*Generated by Manifest CLI v${version}*
EOF
}

# -----------------------------------------------------------------------------
# _manifest_format_kac_block
# -----------------------------------------------------------------------------

@test "format_kac_block: stub changelog → minimal block" {
    local f="${SCRATCH}/CHANGELOG_v46.13.6.md"
    seed_auto_changelog "$f" "patch"

    run _manifest_format_kac_block "$f"
    [ "$status" -eq 0 ]
    echo "$output" | head -1 | grep -qE '^## \[46\.13\.6\] - [0-9]{4}-[0-9]{2}-[0-9]{2}$'
    echo "$output" | grep -q "^\*\*Release Type:\*\* Patch$"
    echo "$output" | grep -q "^### Summary$"
    echo "$output" | grep -q "No notable user-facing changes"
    # No leftover auto-gen scaffolding.
    ! echo "$output" | grep -q "^# Changelog v"
    ! echo "$output" | grep -q "^## Highlights"
    ! echo "$output" | grep -q "Generated by Manifest CLI"
    ! echo "$output" | grep -q "^\*\*Release Date:\*\*"
}

@test "format_kac_block: substantive multi-section changelog" {
    local f="${SCRATCH}/CHANGELOG_v46.7.0.md"
    seed_auto_changelog "$f" "minor" "### Summary
- Notable changes: 2

### Bug Fixes
- Correct Homebrew formula SHA for v46.6.0

### Documentation
- Documentation review: Documentation impact appears low."

    run _manifest_format_kac_block "$f"
    [ "$status" -eq 0 ]
    echo "$output" | grep -qE '^## \[46\.7\.0\] - '
    echo "$output" | grep -q '\*\*Release Type:\*\* Minor'
    echo "$output" | grep -q '### Bug Fixes'
    echo "$output" | grep -q 'Correct Homebrew formula SHA for v46.6.0'
    echo "$output" | grep -q '### Documentation'
}

@test "format_kac_block: filename without recognizable version → returns 1" {
    local f="${SCRATCH}/NOT_A_CHANGELOG.md"
    echo "garbage" > "$f"
    run _manifest_format_kac_block "$f"
    [ "$status" -eq 1 ]
}

# -----------------------------------------------------------------------------
# regenerate_root_changelog
# -----------------------------------------------------------------------------

@test "regenerate: writes header + current entry when archive is empty" {
    seed_auto_changelog "docs/CHANGELOG_v46.13.6.md" "patch"

    run regenerate_root_changelog "$SCRATCH" "46.13.6"
    [ "$status" -eq 0 ]
    [ -f "${SCRATCH}/CHANGELOG.md" ]
    head -1 "${SCRATCH}/CHANGELOG.md" | grep -q "^# Changelog$"
    grep -q "^## \[46\.13\.6\]" "${SCRATCH}/CHANGELOG.md"
}

@test "regenerate: includes archived entries newest first" {
    seed_auto_changelog "docs/CHANGELOG_v46.13.6.md" "patch"
    mkdir -p docs/zArchive/v46
    seed_auto_changelog "docs/zArchive/v46/CHANGELOG_v46.13.0.md" "minor"
    seed_auto_changelog "docs/zArchive/v46/CHANGELOG_v46.7.0.md" "minor"
    seed_auto_changelog "docs/zArchive/v46/CHANGELOG_v46.3.0.md" "minor"

    run regenerate_root_changelog "$SCRATCH" "46.13.6"
    [ "$status" -eq 0 ]

    # All four versions present.
    grep -q "^## \[46\.13\.6\]" "${SCRATCH}/CHANGELOG.md"
    grep -q "^## \[46\.13\.0\]" "${SCRATCH}/CHANGELOG.md"
    grep -q "^## \[46\.7\.0\]" "${SCRATCH}/CHANGELOG.md"
    grep -q "^## \[46\.3\.0\]" "${SCRATCH}/CHANGELOG.md"

    # Newest first ordering: 46.13.6 line < 46.13.0 line < 46.7.0 line < 46.3.0 line.
    local p1 p2 p3 p4
    p1=$(grep -n "^## \[46\.13\.6\]" "${SCRATCH}/CHANGELOG.md" | cut -d: -f1)
    p2=$(grep -n "^## \[46\.13\.0\]" "${SCRATCH}/CHANGELOG.md" | cut -d: -f1)
    p3=$(grep -n "^## \[46\.7\.0\]" "${SCRATCH}/CHANGELOG.md" | cut -d: -f1)
    p4=$(grep -n "^## \[46\.3\.0\]" "${SCRATCH}/CHANGELOG.md" | cut -d: -f1)
    [ "$p1" -lt "$p2" ]
    [ "$p2" -lt "$p3" ]
    [ "$p3" -lt "$p4" ]
}

@test "regenerate: missing active changelog → warn + skip, no root file written" {
    # No docs/CHANGELOG_v*.md seeded.
    run regenerate_root_changelog "$SCRATCH" "46.13.6"
    [ "$status" -eq 0 ]
    echo "$output" | grep -q "skipping root CHANGELOG"
    [ ! -f "${SCRATCH}/CHANGELOG.md" ]
}

@test "regenerate: existing root CHANGELOG content is replaced (no preservation)" {
    seed_auto_changelog "docs/CHANGELOG_v46.13.6.md" "patch"
    cat > "${SCRATCH}/CHANGELOG.md" <<'EOF'
# Old Changelog

Hand-crafted content from before; should not survive.

## [99.0.0] - 2099-01-01
EOF

    regenerate_root_changelog "$SCRATCH" "46.13.6"
    ! grep -q "Hand-crafted content from before" "${SCRATCH}/CHANGELOG.md"
    ! grep -q "99.0.0" "${SCRATCH}/CHANGELOG.md"
    grep -q "^## \[46\.13\.6\]" "${SCRATCH}/CHANGELOG.md"
}

@test "regenerate: honors MANIFEST_CLI_DOCS_FOLDER override" {
    # User configures docs folder to "documentation" instead of "docs".
    export MANIFEST_CLI_DOCS_FOLDER="documentation"
    export MANIFEST_CLI_DOCS_ARCHIVE_FOLDER="documentation/zArchive"
    mkdir -p documentation/zArchive
    seed_auto_changelog "documentation/CHANGELOG_v46.13.6.md" "patch"

    run regenerate_root_changelog "$SCRATCH" "46.13.6"
    [ "$status" -eq 0 ]
    [ -f "${SCRATCH}/CHANGELOG.md" ]
    grep -q "^## \[46\.13\.6\]" "${SCRATCH}/CHANGELOG.md"
    # The default `docs/` path was never consulted (no file there).
    [ ! -f "${SCRATCH}/docs/CHANGELOG_v46.13.6.md" ]
}
