#!/bin/bash

# Manifest Documentation Module
# Orchestrates document generation using atomized modules

# Documentation module - uses MANIFEST_CLI_PROJECT_ROOT from core module

# Get configurable documentation directory
get_docs_dir() {
    get_docs_folder "$MANIFEST_CLI_PROJECT_ROOT"
}

# Import required modules
MANIFEST_CLI_SCRIPT_DIR="$(get_script_dir)"
source "$(dirname "$MANIFEST_CLI_SCRIPT_DIR")/git/manifest-git-changes.sh"
source "$(dirname "$MANIFEST_CLI_SCRIPT_DIR")/docs/manifest-markdown-templates.sh"
source "$(dirname "$MANIFEST_CLI_SCRIPT_DIR")/docs/manifest-markdown-validation.sh"
# manifest_make_scratch_path lives here — every temp-file site below depends
# on it. Idempotent thanks to the module's load guard.
source "$(dirname "$MANIFEST_CLI_SCRIPT_DIR")/system/manifest-install-paths.sh"

MANIFEST_CLI_README_VERSION_START="<!-- manifest:readme-version:start -->"
MANIFEST_CLI_README_VERSION_END="<!-- manifest:readme-version:end -->"
MANIFEST_CLI_ROOT_CHANGELOG_START="<!-- manifest:root-changelog:start -->"
MANIFEST_CLI_ROOT_CHANGELOG_END="<!-- manifest:root-changelog:end -->"
MANIFEST_CLI_INDEX_METADATA_START="<!-- manifest:index-metadata:start -->"
MANIFEST_CLI_INDEX_METADATA_END="<!-- manifest:index-metadata:end -->"
MANIFEST_CLI_INDEX_CURRENT_RELEASE_START="<!-- manifest:index-current-release:start -->"
MANIFEST_CLI_INDEX_CURRENT_RELEASE_END="<!-- manifest:index-current-release:end -->"
MANIFEST_CLI_DOCS_SITE_MANAGED_MARKER="Managed by Manifest CLI docs site generation"

manifest_file_has_managed_block() {
    local file="$1"
    local start_marker="$2"
    local end_marker="$3"

    [[ -f "$file" ]] || return 1
    grep -Fqx "$start_marker" "$file" && grep -Fqx "$end_marker" "$file"
}

manifest_replace_managed_block() {
    local file="$1"
    local start_marker="$2"
    local end_marker="$3"
    local content_file="$4"
    local start_line end_line temp_file

    start_line=$(grep -nFx "$start_marker" "$file" | head -1 | cut -d: -f1)
    end_line=$(grep -nFx "$end_marker" "$file" | head -1 | cut -d: -f1)

    if [[ -z "$start_line" ]] || [[ -z "$end_line" ]] || (( end_line <= start_line )); then
        return 1
    fi

    temp_file=$(mktemp "$(manifest_make_scratch_path docs)/tmp.XXXXXXXX")
    if (( start_line > 1 )); then
        head -n $((start_line - 1)) "$file" > "$temp_file"
    else
        : > "$temp_file"
    fi

    printf '%s\n' "$start_marker" >> "$temp_file"
    cat "$content_file" >> "$temp_file"
    printf '%s\n' "$end_marker" >> "$temp_file"
    tail -n +$((end_line + 1)) "$file" >> "$temp_file"
    mv "$temp_file" "$file"
}

manifest_is_legacy_generated_readme() {
    local readme_file="$1"
    [[ -f "$readme_file" ]] || return 1

    if grep -Fq "This project uses [Manifest CLI]" "$readme_file"; then
        return 0
    fi
    if grep -Fq "This repo is versioned and documented by [Manifest CLI]" "$readme_file"; then
        return 0
    fi
    if grep -Fq "| **CLI Version** |" "$readme_file"; then
        return 0
    fi

    return 1
}

manifest_is_legacy_generated_root_changelog() {
    local changelog_file="$1"
    [[ -f "$changelog_file" ]] || return 1
    grep -Fq "Generated by Manifest CLI v" "$changelog_file"
}

manifest_is_legacy_generated_index() {
    local index_file="$1"
    [[ -f "$index_file" ]] || return 1
    grep -Fq "<!-- Manifest CLI v" "$index_file" || grep -Fq "# Manifest CLI Documentation" "$index_file"
}

generate_external_index_metadata_block() {
    local version="$1"
    cat << EOF
**Version:** $version | **Updated:** $(date -u '+%Y-%m-%d')
EOF
}

generate_external_index_current_release_block() {
    local version="$1"

    cat << EOF
| Document | Description |
| -------- | ----------- |
| [CHANGELOG.md](../CHANGELOG.md) | All releases, newest first |
EOF
}

write_external_docs_index() {
    local index_file="$1"
    local version="$2"
    local repo_name
    repo_name="$(manifest_repo_display_name "$MANIFEST_CLI_PROJECT_ROOT")"
    local metadata_file current_release_file
    metadata_file=$(mktemp "$(manifest_make_scratch_path docs)/tmp.XXXXXXXX")
    current_release_file=$(mktemp "$(manifest_make_scratch_path docs)/tmp.XXXXXXXX")

    generate_external_index_metadata_block "$version" > "$metadata_file"
    generate_external_index_current_release_block "$version" > "$current_release_file"

    cat > "$index_file" << EOF
# ${repo_name} Documentation

${MANIFEST_CLI_INDEX_METADATA_START}
$(cat "$metadata_file")
${MANIFEST_CLI_INDEX_METADATA_END}

## Current Release
${MANIFEST_CLI_INDEX_CURRENT_RELEASE_START}
$(cat "$current_release_file")
${MANIFEST_CLI_INDEX_CURRENT_RELEASE_END}
EOF

    rm -f "$metadata_file" "$current_release_file"
}

_manifest_docs_config_bool() {
    local value="$1"
    local default="${2:-true}"
    if [[ -z "$value" ]]; then
        value="$default"
    fi
    is_truthy "$value"
}

_manifest_docs_site_enabled() {
    _manifest_docs_config_bool "${MANIFEST_CLI_DOCS_GENERATE_SITE:-false}" "false" || \
        _manifest_docs_config_bool "${MANIFEST_CLI_DOCS_SITE_ENABLED:-false}" "false"
}

_manifest_docs_site_workflow_enabled() {
    _manifest_docs_config_bool "${MANIFEST_CLI_DOCS_GENERATE_SITE_WORKFLOW:-true}" "true"
}

_manifest_docs_write_managed_file() {
    local file="$1"
    local marker="$2"
    local content_file="$3"

    if [[ -f "$file" ]] && ! grep -Fq "$marker" "$file"; then
        log_error "Refusing to overwrite unmanaged docs site file: $file"
        return 1
    fi

    mkdir -p "$(dirname "$file")"
    cp "$content_file" "$file"
}

_manifest_docs_repo_title() {
    local project_root="${1:-$MANIFEST_CLI_PROJECT_ROOT}"
    local configured="${MANIFEST_CLI_DOCS_SITE_TITLE:-}"
    if [[ -n "$configured" ]]; then
        printf '%s\n' "$configured"
        return 0
    fi
    manifest_repo_display_name "$project_root"
}

_manifest_docs_site_palette_css() {
    cat << EOF
:root {
  --manifest-primary: ${MANIFEST_CLI_DOCS_SITE_PALETTE_PRIMARY:-#2563eb};
  --manifest-accent: ${MANIFEST_CLI_DOCS_SITE_PALETTE_ACCENT:-#14b8a6};
  --manifest-background: ${MANIFEST_CLI_DOCS_SITE_PALETTE_BACKGROUND:-#ffffff};
  --manifest-surface: ${MANIFEST_CLI_DOCS_SITE_PALETTE_SURFACE:-#f8fafc};
  --manifest-text: ${MANIFEST_CLI_DOCS_SITE_PALETTE_TEXT:-#111827};
  --manifest-muted: ${MANIFEST_CLI_DOCS_SITE_PALETTE_MUTED:-#64748b};
}

body {
  margin: 0;
  color: var(--manifest-text);
  background: var(--manifest-background);
  font-family: -apple-system, BlinkMacSystemFont, "Segoe UI", sans-serif;
  line-height: 1.6;
}

.page {
  max-width: 960px;
  margin: 0 auto;
  padding: 48px 24px;
}

.masthead {
  border-bottom: 1px solid #e5e7eb;
  margin-bottom: 32px;
  padding-bottom: 24px;
}

.masthead h1 {
  margin: 0 0 8px;
  font-size: 2.25rem;
  letter-spacing: 0;
}

.masthead p {
  color: var(--manifest-muted);
  margin: 0;
}

.doc-grid {
  display: grid;
  gap: 16px;
  grid-template-columns: repeat(auto-fit, minmax(220px, 1fr));
}

.doc-link {
  border: 1px solid #e5e7eb;
  border-radius: 8px;
  background: var(--manifest-surface);
  padding: 16px;
}

a {
  color: var(--manifest-primary);
}
EOF
}

_manifest_docs_generate_site() {
    local version="$1"
    local timestamp="$2"
    local scope="${3:-repo}"
    local project_root="${4:-$MANIFEST_CLI_PROJECT_ROOT}"
    local docs_dir="${5:-$(get_docs_dir)}"
    local source_dir="${MANIFEST_CLI_DOCS_SITE_SOURCE_DIR:-docs-site}"
    local site_root="$project_root/$source_dir"
    local title description
    title="$(_manifest_docs_repo_title "$project_root")"
    description="${MANIFEST_CLI_DOCS_SITE_DESCRIPTION:-Documentation for $title}"

    local config_file index_file layout_file css_file gitignore_file content_file
    config_file=$(mktemp "$(manifest_make_scratch_path docs)/tmp.XXXXXXXX")
    index_file=$(mktemp "$(manifest_make_scratch_path docs)/tmp.XXXXXXXX")
    layout_file=$(mktemp "$(manifest_make_scratch_path docs)/tmp.XXXXXXXX")
    css_file=$(mktemp "$(manifest_make_scratch_path docs)/tmp.XXXXXXXX")
    gitignore_file=$(mktemp "$(manifest_make_scratch_path docs)/tmp.XXXXXXXX")

    cat > "$config_file" << EOF
# $MANIFEST_CLI_DOCS_SITE_MANAGED_MARKER
title: "$title"
description: "$description"
theme: minima
markdown: kramdown
exclude:
  - .jekyll-cache
  - .bundle
  - vendor
EOF

    cat > "$index_file" << EOF
---
layout: default
title: Home
---
<!-- $MANIFEST_CLI_DOCS_SITE_MANAGED_MARKER -->

<main class="page">
  <header class="masthead">
    <h1>$title</h1>
    <p>$description</p>
  </header>

  <section class="doc-grid">
    <article class="doc-link">
      <h2>README</h2>
      <p><a href="README.md">Project overview</a></p>
    </article>
    <article class="doc-link">
      <h2>Changelog</h2>
      <p><a href="CHANGELOG.md">Release history for v$version</a></p>
    </article>
    <article class="doc-link">
      <h2>Documentation Index</h2>
      <p><a href="${docs_dir#"$project_root"/}/INDEX.md">Generated documentation index</a></p>
    </article>
  </section>
</main>
EOF

    cat > "$layout_file" << EOF
<!-- $MANIFEST_CLI_DOCS_SITE_MANAGED_MARKER -->
<!doctype html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>{{ page.title }} | {{ site.title }}</title>
    <link rel="stylesheet" href="{{ '/assets/css/manifest.css' | relative_url }}">
  </head>
  <body>
    {{ content }}
  </body>
</html>
EOF

    {
        printf '/* %s */\n' "$MANIFEST_CLI_DOCS_SITE_MANAGED_MARKER"
        _manifest_docs_site_palette_css
        if [[ -n "${MANIFEST_CLI_DOCS_SITE_CUSTOM_CSS:-}" ]]; then
            printf '\n@import url("%s");\n' "$MANIFEST_CLI_DOCS_SITE_CUSTOM_CSS"
        fi
    } > "$css_file"

    cat > "$gitignore_file" << EOF
# $MANIFEST_CLI_DOCS_SITE_MANAGED_MARKER
_site/
.jekyll-cache/
.sass-cache/
.bundle/
vendor/
.jekyll-metadata
EOF

    _manifest_docs_write_managed_file "$site_root/_config.yml" "$MANIFEST_CLI_DOCS_SITE_MANAGED_MARKER" "$config_file" || return 1
    _manifest_docs_write_managed_file "$site_root/index.md" "$MANIFEST_CLI_DOCS_SITE_MANAGED_MARKER" "$index_file" || return 1
    _manifest_docs_write_managed_file "$site_root/_layouts/default.html" "$MANIFEST_CLI_DOCS_SITE_MANAGED_MARKER" "$layout_file" || return 1
    _manifest_docs_write_managed_file "$site_root/assets/css/manifest.css" "$MANIFEST_CLI_DOCS_SITE_MANAGED_MARKER" "$css_file" || return 1
    _manifest_docs_write_managed_file "$site_root/.gitignore" "$MANIFEST_CLI_DOCS_SITE_MANAGED_MARKER" "$gitignore_file" || return 1

    rm -f "$config_file" "$index_file" "$layout_file" "$css_file" "$gitignore_file"

    if _manifest_docs_site_workflow_enabled; then
        _manifest_docs_generate_pages_workflow "$project_root" "$source_dir" || return 1
    fi

    _manifest_docs_enable_pages_if_requested "$project_root"
}

_manifest_docs_generate_pages_workflow() {
    local project_root="$1"
    local source_dir="$2"
    local workflow_file="$project_root/.github/workflows/manifest-docs-pages.yml"
    local content_file
    content_file=$(mktemp "$(manifest_make_scratch_path docs)/tmp.XXXXXXXX")

    cat > "$content_file" << EOF
# $MANIFEST_CLI_DOCS_SITE_MANAGED_MARKER
name: Manifest Docs Pages

on:
  push:
    branches:
      - main
    paths:
      - "$source_dir/**"
      - "README.md"
      - "CHANGELOG.md"
      - "docs/**"
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: pages
  cancel-in-progress: false

jobs:
  build:
    runs-on: ubuntu-latest
    outputs:
      pages_enabled: \${{ steps.pages_check.outputs.enabled }}
    steps:
      - uses: actions/checkout@v6
      - name: Detect GitHub Pages availability
        id: pages_check
        env:
          GH_TOKEN: \${{ github.token }}
        run: |
          if gh api "repos/\${{ github.repository }}/pages" >/dev/null 2>&1; then
            echo "enabled=true" >> "\$GITHUB_OUTPUT"
            echo "GitHub Pages is enabled - building and deploying the docs site."
          else
            echo "enabled=false" >> "\$GITHUB_OUTPUT"
            echo "::notice::GitHub Pages is not enabled for \${{ github.repository }} (e.g. a private repo on a plan tier without Pages). Skipping build/deploy; the site publishes automatically once Pages is enabled."
          fi
      - if: steps.pages_check.outputs.enabled == 'true'
        uses: actions/configure-pages@v6
      - name: Prepare Manifest docs source
        if: steps.pages_check.outputs.enabled == 'true'
        run: |
          rm -rf .manifest-pages-src
          mkdir -p .manifest-pages-src
          cp -R "$source_dir"/. .manifest-pages-src/
          [ -f README.md ] && cp README.md .manifest-pages-src/README.md
          [ -f CHANGELOG.md ] && cp CHANGELOG.md .manifest-pages-src/CHANGELOG.md
          if [ -d docs ]; then
            mkdir -p .manifest-pages-src/docs
            cp -R docs/. .manifest-pages-src/docs/
          fi
      - if: steps.pages_check.outputs.enabled == 'true'
        uses: actions/jekyll-build-pages@v1
        with:
          source: ./.manifest-pages-src
          destination: ./_site
      - if: steps.pages_check.outputs.enabled == 'true'
        uses: actions/upload-pages-artifact@v5
  deploy:
    if: needs.build.outputs.pages_enabled == 'true'
    environment:
      name: github-pages
      url: \${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    needs: build
    steps:
      - id: deployment
        uses: actions/deploy-pages@v5
EOF

    _manifest_docs_write_managed_file "$workflow_file" "$MANIFEST_CLI_DOCS_SITE_MANAGED_MARKER" "$content_file"
    local status=$?
    rm -f "$content_file"
    return "$status"
}

# Best-effort GitHub Pages enablement. This NEVER interrupts a Manifest run:
# the managed docs site and the Pages workflow are already committed, so if
# enablement can't complete (commonly a private repo on a plan tier without
# Pages, HTTP 422) we surface a clear notice and continue. Pages publishes
# automatically the moment it becomes available for the repo.
_manifest_docs_enable_pages_if_requested() {
    local project_root="$1"
    _manifest_docs_config_bool "${MANIFEST_CLI_DOCS_SITE_ENABLE_PAGES:-true}" "true" || return 0

    local slug=""
    if declare -F manifest_origin_repo_slug >/dev/null 2>&1; then
        slug="$(MANIFEST_CLI_PROJECT_ROOT="$project_root" manifest_origin_repo_slug 2>/dev/null || true)"
    fi

    if [[ -z "$slug" ]] || ! command -v gh >/dev/null 2>&1; then
        log_warning "Skipping GitHub Pages enablement; gh or repo slug unavailable."
        log_info "The docs site and Pages workflow are committed and will publish once Pages is available for this repository."
        return 0
    fi

    local gh_error
    if gh_error="$(gh api --method POST "repos/$slug/pages" -f build_type=workflow 2>&1 >/dev/null)"; then
        log_success "GitHub Pages enabled for $slug"
        return 0
    fi

    if gh_error="$(gh api --method PATCH "repos/$slug/pages" -f build_type=workflow 2>&1 >/dev/null)"; then
        log_success "GitHub Pages workflow publishing configured for $slug"
        return 0
    fi

    _manifest_docs_notify_pages_unavailable "$slug" "$gh_error"
    return 0
}

# Emit a non-fatal notice when Pages could not be enabled, explaining the most
# likely cause (private repo on a plan without Pages) without failing the run.
_manifest_docs_notify_pages_unavailable() {
    local slug="$1"
    local gh_error="$2"

    log_warning "GitHub Pages was not enabled for $slug; continuing without interruption."
    if [[ "$gh_error" == *"does not support"* || "$gh_error" == *"422"* ]]; then
        log_info "This typically means the repository is private on a GitHub plan that does not include Pages for private repositories. The docs site and Pages workflow are committed and will publish automatically once Pages becomes available (upgrade the plan or make the repository public)."
    else
        log_info "The docs site and Pages workflow are committed and will publish automatically once Pages becomes available for this repository."
    fi
    if [[ -n "$gh_error" ]]; then
        log_info "gh reported: ${gh_error//$'\n'/ }"
    fi
}

# Update README version information
# Preserves user-crafted README content. Only updates inline version strings
# and the version metadata section if one already exists. Never prepends a
# new metadata block to a README that doesn't have one.
update_readme_version() {
    local version="$1"
    local timestamp="$2"

    log_info "Updating README version information..."

    local readme_file="$MANIFEST_CLI_PROJECT_ROOT/README.md"

    if [[ ! -f "$readme_file" ]]; then
        log_warning "README.md not found, skipping version update"
        return 0
    fi

    if manifest_is_canonical_repo "$MANIFEST_CLI_PROJECT_ROOT"; then
        local temp_file
        temp_file=$(mktemp "$(manifest_make_scratch_path docs)/tmp.XXXXXXXX")

        if grep -q "## 📋 Version Information" "$readme_file"; then
            # README has a version metadata section — replace it in place
            local version_section
            version_section=$(generate_readme_version_section "$version" "$timestamp")
            local version_section_file
            version_section_file=$(mktemp "$(manifest_make_scratch_path docs)/tmp.XXXXXXXX")
            echo "$version_section" > "$version_section_file"

            local start_line end_line
            start_line=$(grep -n "## 📋 Version Information" "$readme_file" | head -1 | cut -d: -f1)
            end_line=$(tail -n +$((start_line + 1)) "$readme_file" | grep -n "^## " | head -1 | cut -d: -f1)

            if [[ -n "$end_line" ]]; then
                end_line=$((start_line + end_line - 1))
            else
                end_line=$(wc -l < "$readme_file")
            fi

            if [[ "$start_line" -gt 1 ]]; then
                head -n $((start_line - 1)) "$readme_file" > "$temp_file"
            else
                : > "$temp_file"
            fi
            cat "$version_section_file" >> "$temp_file"
            tail -n +$((end_line + 1)) "$readme_file" >> "$temp_file"

            rm -f "$version_section_file"
            mv "$temp_file" "$readme_file"
        else
            rm -f "$temp_file"
            local old_version=""
            if [[ -f "$MANIFEST_CLI_PROJECT_ROOT/VERSION" ]]; then
                old_version=$(grep -oE '`[0-9]+\.[0-9]+\.[0-9]+`' "$readme_file" | head -1 | tr -d '`')
            fi
            if [[ -n "$old_version" ]] && [[ "$old_version" != "$version" ]]; then
                sed -i'' -e "s|\`${old_version}\`|\`${version}\`|g" "$readme_file"
                rm -f "${readme_file}-e"
                log_debug "Updated inline version references: $old_version -> $version"
            fi
        fi

        log_success "README version information updated"
        return 0
    fi

    local version_section_file
    version_section_file=$(mktemp "$(manifest_make_scratch_path docs)/tmp.XXXXXXXX")
    generate_readme_version_section "$version" "$timestamp" > "$version_section_file"

    if manifest_is_legacy_generated_readme "$readme_file"; then
        create_default_readme "$readme_file"
    fi

    if manifest_file_has_managed_block "$readme_file" "$MANIFEST_CLI_README_VERSION_START" "$MANIFEST_CLI_README_VERSION_END"; then
        manifest_replace_managed_block "$readme_file" "$MANIFEST_CLI_README_VERSION_START" "$MANIFEST_CLI_README_VERSION_END" "$version_section_file"
    else
        log_info "Preserving existing README formatting; no Manifest-managed version block found."
    fi

    rm -f "$version_section_file"

    log_success "README version information updated"
}

# Generate documentation index
# If an INDEX.md already exists, updates version numbers and release note
# links in place, preserving user-crafted structure and formatting.
# Only creates the file from a template when it doesn't exist at all.
generate_docs_index() {
    local version="$1"

    log_info "Generating documentation index..."

    local index_file="$(get_docs_dir)/INDEX.md"

    if manifest_is_canonical_repo "$MANIFEST_CLI_PROJECT_ROOT"; then
        if [[ -f "$index_file" ]]; then
            local old_version=""
            old_version=$(grep -oE '`[0-9]+\.[0-9]+\.[0-9]+`' "$index_file" | head -1 | tr -d '`')
            if [[ -n "$old_version" ]] && [[ "$old_version" != "$version" ]]; then
                sed -i'' -e "s|\`${old_version}\`|\`${version}\`|g" "$index_file"
            fi

            sed -i'' -e "s|^\*\*Version:\*\* [0-9][0-9.]*|\*\*Version:\*\* $version|" "$index_file"

            local today
            today=$(date -u '+%Y-%m-%d')
            sed -i'' -e "s|^\*\*Updated:\*\* [0-9-]*|\*\*Updated:\*\* $today|" "$index_file"
            sed -i'' -e "s|\*\*Updated:\*\* [0-9-]*|\*\*Updated:\*\* $today|g" "$index_file"
            rm -f "${index_file}-e"

            log_success "Documentation index updated: $index_file"
            return 0
        fi

        cat > "$index_file" << EOF
# Manifest CLI Documentation

**Version:** $version | **Updated:** $(date -u '+%Y-%m-%d')

---

## Getting Started

| Document | Description |
| -------- | ----------- |
| [Installation Guide](INSTALLATION.md) | Setup, upgrade, uninstall, and troubleshooting |
| [User Guide](USER_GUIDE.md) | Workflows, daily commands, and configuration |
| [Examples](EXAMPLES.md) | Real-world workflow recipes |

## Reference

| Document | Description |
| -------- | ----------- |
| [Command Reference](COMMAND_REFERENCE.md) | Every command, flag, and option |
| [YAML config example](../examples/manifest.config.yaml.example) | Full schema with all keys + comments |

## Releases

| Document | Description |
| -------- | ----------- |
| [CHANGELOG.md](../CHANGELOG.md) | All releases, newest first |

---

## Quick Start

\`\`\`bash
# Install
brew tap fidenceio/tap && brew install manifest

# Prepare a release locally
manifest prep repo patch

# Publish a release
manifest ship repo minor

# Get help
manifest --help
\`\`\`

<!-- Manifest CLI v$version -->
EOF

        log_success "Documentation index generated: $index_file"
        return 0
    fi

    if [[ -f "$index_file" ]]; then
        if manifest_is_legacy_generated_index "$index_file"; then
            write_external_docs_index "$index_file" "$version"
        elif manifest_file_has_managed_block "$index_file" "$MANIFEST_CLI_INDEX_METADATA_START" "$MANIFEST_CLI_INDEX_METADATA_END" && manifest_file_has_managed_block "$index_file" "$MANIFEST_CLI_INDEX_CURRENT_RELEASE_START" "$MANIFEST_CLI_INDEX_CURRENT_RELEASE_END"; then
            local metadata_file current_release_file
            metadata_file=$(mktemp "$(manifest_make_scratch_path docs)/tmp.XXXXXXXX")
            current_release_file=$(mktemp "$(manifest_make_scratch_path docs)/tmp.XXXXXXXX")
            generate_external_index_metadata_block "$version" > "$metadata_file"
            generate_external_index_current_release_block "$version" > "$current_release_file"
            manifest_replace_managed_block "$index_file" "$MANIFEST_CLI_INDEX_METADATA_START" "$MANIFEST_CLI_INDEX_METADATA_END" "$metadata_file"
            manifest_replace_managed_block "$index_file" "$MANIFEST_CLI_INDEX_CURRENT_RELEASE_START" "$MANIFEST_CLI_INDEX_CURRENT_RELEASE_END" "$current_release_file"
            rm -f "$metadata_file" "$current_release_file"
        else
            log_info "Preserving existing documentation index formatting; no Manifest-managed blocks found."
            return 0
        fi

        log_success "Documentation index updated: $index_file"
        return 0
    fi

    write_external_docs_index "$index_file" "$version"
    log_success "Documentation index generated: $index_file"
}

# Parse a docs.retain spec into kind and value.
#   "N versions" → kind=versions, value=N
#   "N days"     → kind=days, value=N
#   "off" or ""  → kind=off, value=0
# Returns 0 on success, 1 on malformed input. Output written to the named
# variables in $2 (kind) and $3 (value).
_manifest_parse_retention() {
    local raw="$1"
    local _outkind="$2"
    local _outval="$3"

    raw="$(printf '%s' "$raw" | tr -s '[:space:]' ' ')"
    raw="${raw# }"; raw="${raw% }"

    if [[ -z "$raw" || "$raw" == "off" ]]; then
        printf -v "$_outkind" '%s' "off"
        printf -v "$_outval" '%s' "0"
        return 0
    fi

    local num="${raw%% *}"
    local unit="${raw#* }"
    [[ "$num" =~ ^[0-9]+$ ]] || return 1

    case "$unit" in
        version|versions)
            printf -v "$_outkind" '%s' "versions"
            printf -v "$_outval" '%s' "$num"
            ;;
        day|days)
            printf -v "$_outkind" '%s' "days"
            printf -v "$_outval" '%s' "$num"
            ;;
        *)
            return 1
            ;;
    esac
}

# --- Root CHANGELOG.md prepend ----------------------------------------------
#
# Root CHANGELOG.md is the single source of truth for changelog history.
# Each ship prepends a Keep-a-Changelog block under the `# Changelog`
# header, then enforces docs.retain on the resulting section count.

# Title-case a release type ("patch" → "Patch"). Echoes the input
# unchanged when the type is empty or already capitalized.
_manifest_titlecase_release_type() {
    local t="$1"
    case "$t" in
        patch) printf 'Patch' ;;
        minor) printf 'Minor' ;;
        major) printf 'Major' ;;
        revision) printf 'Revision' ;;
        *) printf '%s' "$t" ;;
    esac
}

# Build a Keep-a-Changelog block from a version, timestamp, release type,
# and an analyzed-changes file (the output of analyze_changes). The body
# is the content following `## Highlights for vX` in the changes file.
_manifest_build_changelog_entry() {
    local version="$1"
    local timestamp="$2"
    local release_type="$3"
    local changes_file="$4"

    local release_date="${timestamp%% *}"
    [[ -n "$release_date" ]] || release_date="$(date -u '+%Y-%m-%d')"

    local rtype
    rtype="$(_manifest_titlecase_release_type "$release_type")"

    local body=""
    if [[ -f "$changes_file" ]]; then
        body="$(awk '
            /^## Highlights for v/ { capture=1; next }
            capture { print }
        ' "$changes_file" | awk '
            { lines[NR]=$0 }
            END {
                start=1
                while (start<=NR && lines[start]=="") start++
                end=NR
                while (end>=start && lines[end]=="") end--
                for (i=start; i<=end; i++) print lines[i]
            }
        ')"
    fi

    printf '## [%s] - %s\n\n' "$version" "$release_date"
    if [[ -n "$body" ]]; then
        [[ -n "$rtype" ]] && printf '**Release Type:** %s\n\n' "$rtype"
        printf '%s\n' "$body"
    else
        if [[ -n "$rtype" ]]; then
            printf '**Release Type:** %s — no user-facing changes.\n' "$rtype"
        else
            printf 'No user-facing changes.\n'
        fi
    fi
}

# Prepend (or replace, on re-ship of the same version) a changelog entry
# at the top of root CHANGELOG.md. Creates the file with a `# Changelog`
# header if it doesn't exist yet, or rewrites a legacy auto-generated
# header. Then enforces docs.retain on section count.
prepend_root_changelog_entry() {
    local project_root="$1"
    local version="$2"
    local timestamp="$3"
    local release_type="$4"
    local changes_file="$5"

    local root_changelog="${project_root}/CHANGELOG.md"
    local entry_file
    entry_file="$(mktemp "$(manifest_make_scratch_path docs)/tmp.XXXXXXXX")"
    _manifest_build_changelog_entry "$version" "$timestamp" "$release_type" "$changes_file" \
        > "$entry_file"

    local existing_body_file
    existing_body_file="$(mktemp "$(manifest_make_scratch_path docs)/tmp.XXXXXXXX")"
    if [[ -f "$root_changelog" ]] && ! manifest_is_legacy_generated_root_changelog "$root_changelog"; then
        # Strip the leading `# Changelog\n\n` header (if present); keep the rest.
        # Also drop any existing `## [X.Y.Z]` section matching the current
        # version, so re-shipping the same version replaces rather than
        # duplicates.
        awk -v ver="$version" '
            BEGIN { skip_header=1; skip_dup=0 }
            skip_header && NR==1 && $0 ~ /^# Changelog[[:space:]]*$/ { next }
            skip_header && NR<=2 && $0 ~ /^[[:space:]]*$/ { next }
            { skip_header=0 }
            $0 ~ "^## \\[" ver "\\] - " { skip_dup=1; next }
            skip_dup && /^## \[/ { skip_dup=0 }
            !skip_dup { print }
        ' "$root_changelog" > "$existing_body_file"
    fi

    {
        printf '# Changelog\n\n'
        cat "$entry_file"
        if [[ -s "$existing_body_file" ]]; then
            # Ensure a blank line separates entries.
            local last_char
            last_char="$(tail -c 1 "$entry_file" 2>/dev/null || true)"
            [[ "$last_char" == $'\n' ]] || printf '\n'
            printf '\n'
            cat "$existing_body_file"
        fi
    } > "$root_changelog"

    rm -f "$entry_file" "$existing_body_file"

    _manifest_prune_root_changelog "$root_changelog" \
        "${MANIFEST_CLI_DOCS_RETAIN:-10 versions}"

    log_success "Root CHANGELOG.md updated"
}

# Apply docs.retain to root CHANGELOG.md. "N versions" keeps the top N
# `## [X.Y.Z]` sections; "N days" keeps sections whose date is within
# the last N days; "off" keeps everything. Malformed specs are ignored
# with a warning (the file is left untouched).
_manifest_prune_root_changelog() {
    local file="$1"
    local raw_spec="$2"

    [[ -f "$file" ]] || return 0

    local kind value
    if ! _manifest_parse_retention "$raw_spec" kind value; then
        log_warning "Invalid docs.retain spec: '${raw_spec}' (root CHANGELOG.md not pruned)"
        return 0
    fi
    [[ "$kind" == "off" ]] && return 0

    # For "days", compute the ISO-8601 cutoff date in shell. ISO-8601 dates
    # sort lexicographically, so awk only needs string comparison.
    local cutoff_date=""
    if [[ "$kind" == "days" ]]; then
        # GNU-first (the wrapper forces coreutils' gnubin onto PATH on macOS);
        # BSD `date -v` only as a fallback for native BSDs without GNU date.
        if date -u -d "${value} days ago" '+%Y-%m-%d' >/dev/null 2>&1; then
            cutoff_date="$(date -u -d "${value} days ago" '+%Y-%m-%d')"
        else
            cutoff_date="$(date -u -v "-${value}d" '+%Y-%m-%d')"
        fi
    fi

    local tmp
    tmp="$(mktemp "$(manifest_make_scratch_path docs)/tmp.XXXXXXXX")"
    awk -v kind="$kind" -v value="$value" -v cutoff="$cutoff_date" '
        function flush_section(    keep) {
            if (section_index == 0) return
            keep = 1
            if (kind == "versions") {
                if (kept >= value) keep = 0
            } else if (kind == "days") {
                if (section_date < cutoff) keep = 0
            }
            if (keep) {
                printf "%s", section_buf
                kept++
            }
        }
        BEGIN { in_section = 0; kept = 0; section_index = 0; section_buf = ""; section_date = "" }
        /^## \[[0-9]+\.[0-9]+\.[0-9]+\] - [0-9]{4}-[0-9]{2}-[0-9]{2}/ {
            flush_section()
            section_index++
            section_buf = $0 "\n"
            match($0, /[0-9]{4}-[0-9]{2}-[0-9]{2}/)
            section_date = substr($0, RSTART, RLENGTH)
            in_section = 1
            next
        }
        in_section { section_buf = section_buf $0 "\n"; next }
        { print }
        END { flush_section() }
    ' "$file" > "$tmp"

    # Strip trailing blank lines.
    awk 'BEGIN{n=0} {lines[++n]=$0} END{
        while (n>0 && lines[n] ~ /^[[:space:]]*$/) n--
        for (i=1; i<=n; i++) print lines[i]
    }' "$tmp" > "${tmp}.trim"
    mv "${tmp}.trim" "$file"
    rm -f "$tmp"
}

# -----------------------------------------------------------------------------
# Release-notes synthesis hook (provider-agnostic)
# -----------------------------------------------------------------------------
# Manifest owns the prompt template, the request format, and the validation
# rules for the entry body. The provider command is a thin transport: read
# the request file ($1), call any LLM/service, write a markdown bullet list
# to the output file ($2). No provider-specific text leaks into CHANGELOG.md.

# Build the request file the provider receives.
_manifest_release_notes_build_request() {
    local request_file="$1"
    local version="$2"
    local release_type="$3"
    local timestamp="$4"
    local changes_file="$5"
    local project_root="$6"

    local release_date="${timestamp%% *}"
    [[ -n "$release_date" ]] || release_date="$(date -u '+%Y-%m-%d')"

    local project_slug=""
    if [[ -n "${MANIFEST_CLI_PROJECT_NAME:-}" ]]; then
        project_slug="$MANIFEST_CLI_PROJECT_NAME"
    elif declare -F manifest_origin_repo_slug >/dev/null 2>&1; then
        project_slug="$(manifest_origin_repo_slug 2>/dev/null || true)"
    fi

    {
        cat <<'EOF'
# Manifest Release Notes Request

## Instructions

Generate the body of a release-notes section. Output ONLY a markdown bullet
list — lines starting with `- ` — and nothing else.

Do NOT output:
- Headings, subheadings, or section titles.
- A version number, date, or release-type line.
- Preamble, summary paragraphs, closing prose, or framing language.
- References to yourself, the assistant, the LLM, or the provider.

Each bullet should be:
- One sentence in past-tense imperative voice (for example "Added X",
  "Fixed Y", "Replaced Z with W").
- Concise but specific — name what changed and, where useful, why a user
  cares.
- Free of internal jargon or implementation-only detail. Group related
  commits into a single bullet when sensible. Drop trivial bookkeeping.

Hard limit: 15 bullets.

EOF
        printf '## Metadata\n\n'
        printf -- '- version: %s\n' "$version"
        printf -- '- release_type: %s\n' "$release_type"
        printf -- '- date: %s\n' "$release_date"
        [[ -n "$project_slug" ]] && printf -- '- project: %s\n' "$project_slug"

        printf '\n## Commit subjects\n\n'
        awk '
            /^### Changes[[:space:]]*$/ { in_body=1; next }
            in_body && /^[[:space:]]*$/ { next }
            in_body { print }
        ' "$changes_file" 2>/dev/null || true

        printf '\n## Changed files\n\n'
        if declare -F _manifest_doc_review_changed_files >/dev/null 2>&1; then
            _manifest_doc_review_changed_files "$project_root" 2>/dev/null \
                | sed 's/^/- /' || true
        fi
    } > "$request_file"
}

# Sanitize a provider's output. Strips preamble before the first bullet,
# trailing prose after the last bullet, rejects banned LLM-preamble
# phrases, and caps at 15 bullets. On success, prints cleaned content to
# stdout and returns 0. On any rejection, returns non-zero (no stdout).
_manifest_release_notes_validate_output() {
    local raw_file="$1"
    [[ -f "$raw_file" ]] || return 1

    local cleaned
    cleaned="$(awk '
        BEGIN { started=0; ended=0; n=0; last_bullet=0 }
        !started && /^- / { started=1 }
        started && !ended {
            if (/^- /) {
                lines[++n] = $0
                last_bullet = n
            } else if (/^[[:space:]]+/) {
                lines[++n] = $0
            } else if (/^[[:space:]]*$/) {
                lines[++n] = ""
            } else {
                ended = 1
            }
        }
        END {
            if (last_bullet == 0) exit 1
            bullets = 0
            for (i=1; i<=last_bullet; i++) {
                if (lines[i] ~ /^- /) {
                    bullets++
                    if (bullets > 15) exit
                }
                print lines[i]
            }
        }
    ' "$raw_file")" || return 1

    [[ -n "$cleaned" ]] || return 1

    case "$cleaned" in
        *"As an AI"*|*"As a language model"*|*"Sure, here"*|*"Here are the"*|*"I'll generate"*|*"I'd be happy"*)
            return 1
            ;;
    esac

    printf '%s\n' "$cleaned"
}

# Returns 1 if MANIFEST_CLI_RELEASE_NOTES_REQUIRED is truthy (caller
# should abort), 0 otherwise (caller falls back to local generator).
_manifest_release_notes_required_failure() {
    if is_truthy "${MANIFEST_CLI_RELEASE_NOTES_REQUIRED:-false}"; then
        return 1
    fi
    return 0
}

# Run the configured release-notes provider. On success, replaces the
# `### Changes` body in changes_file with the validated provider output.
# On failure, returns 0 to fall through to the local body unless
# MANIFEST_CLI_RELEASE_NOTES_REQUIRED is truthy (then returns 1).
_manifest_release_notes_run_provider() {
    local version="$1"
    local release_type="$2"
    local timestamp="$3"
    local changes_file="$4"
    local project_root="${MANIFEST_CLI_PROJECT_ROOT:-$(pwd)}"
    local provider="${MANIFEST_CLI_RELEASE_NOTES_PROVIDER:-local}"

    case "$provider" in
        ""|local)
            return 0
            ;;
        command)
            ;;
        *)
            log_warning "Unknown release-notes provider: '$provider' (using local generator)"
            _manifest_release_notes_required_failure || return 1
            return 0
            ;;
    esac

    if [[ -z "${MANIFEST_CLI_RELEASE_NOTES_COMMAND:-}" ]]; then
        log_warning "Release-notes provider 'command' has no MANIFEST_CLI_RELEASE_NOTES_COMMAND (using local generator)"
        _manifest_release_notes_required_failure || return 1
        return 0
    fi

    if [[ ! -x "$MANIFEST_CLI_RELEASE_NOTES_COMMAND" ]]; then
        log_warning "Release-notes provider command is not executable: ${MANIFEST_CLI_RELEASE_NOTES_COMMAND} (using local generator)"
        _manifest_release_notes_required_failure || return 1
        return 0
    fi

    local request_file output_file
    request_file="$(mktemp "$(manifest_make_scratch_path docs)/tmp.XXXXXXXX")"
    output_file="$(mktemp "$(manifest_make_scratch_path docs)/tmp.XXXXXXXX")"
    : > "$output_file"

    _manifest_release_notes_build_request \
        "$request_file" "$version" "$release_type" "$timestamp" \
        "$changes_file" "$project_root"

    log_info "Invoking release-notes provider"
    if ! "$MANIFEST_CLI_RELEASE_NOTES_COMMAND" "$request_file" "$output_file"; then
        log_warning "Release-notes provider exited non-zero (using local generator)"
        rm -f "$request_file" "$output_file"
        _manifest_release_notes_required_failure || return 1
        return 0
    fi

    local validated
    if ! validated="$(_manifest_release_notes_validate_output "$output_file")"; then
        log_warning "Release-notes provider output failed validation (using local generator)"
        rm -f "$request_file" "$output_file"
        _manifest_release_notes_required_failure || return 1
        return 0
    fi

    local new_changes
    new_changes="$(mktemp "$(manifest_make_scratch_path docs)/tmp.XXXXXXXX")"
    {
        printf '## Highlights for v%s\n\n### Changes\n\n' "$version"
        printf '%s\n' "$validated"
    } > "$new_changes"
    mv "$new_changes" "$changes_file"

    rm -f "$request_file" "$output_file"
    log_success "Release-notes provider supplied entry body"
    return 0
}

# Update repository metadata
update_repository_metadata() {
    log_info "Updating repository metadata..."

    # This is a placeholder for repository metadata updates
    # Could include updating GitHub repository description, topics, etc.
    # For now, just log that it's being called
    log_success "Repository metadata update completed"
}

_manifest_docs_fleet_root_summary() {
    local fleet_version="$1"
    local timestamp="$2"
    local release_type="$3"
    local fleet_docs_dir="$4"
    local gen_index="$5"
    local gen_readme_version="$6"

    local service_summary=""
    local service_changes=""

    for service in $MANIFEST_CLI_FLEET_SERVICES; do
        local path excluded version
        path=$(get_fleet_service_property "$service" "path")
        excluded=$(get_fleet_service_property "$service" "excluded" "false")

        [[ "$excluded" == "true" ]] && continue

        version="unknown"
        if [[ -d "$path" ]] && declare -F _get_repo_version >/dev/null 2>&1; then
            version=$(_get_repo_version "$path" 2>/dev/null || echo "unknown")
        elif [[ -f "$path/VERSION" ]]; then
            version=$(cat "$path/VERSION" 2>/dev/null || echo "unknown")
        fi

        service_summary="${service_summary}| ${service} | v${version} | ${release_type} |\n"

        if [[ -d "$path/.git" ]]; then
            local changes
            changes=$(git -C "$path" log --oneline -10 --no-merges 2>/dev/null || echo "  No recent changes")
            service_changes="${service_changes}
### ${service} (v${version})

\`\`\`
${changes}
\`\`\`
"
        fi
    done

    local changes_file
    changes_file=$(mktemp "$(manifest_make_scratch_path docs)/tmp.XXXXXXXX")
    {
        printf '## Highlights for v%s\n\n' "$fleet_version"
        printf '### Service Summary\n\n'
        printf '| Service | Version | Bump Type |\n'
        printf '|---------|---------|-----------|\n'
        printf '%b' "$service_summary"
        printf '\n### Detailed Changes\n%s\n' "$service_changes"
    } > "$changes_file"

    prepend_root_changelog_entry "$MANIFEST_CLI_FLEET_ROOT" "$fleet_version" \
        "$timestamp" "$release_type" "$changes_file" || \
        log_warning "Fleet root CHANGELOG.md update failed"
    rm -f "$changes_file"

    if [[ "$gen_index" == "true" ]]; then
        _manifest_docs_fleet_index "$fleet_version" "$timestamp" "$fleet_docs_dir"
    fi

    if [[ "$gen_readme_version" == "true" ]] && [[ -f "$MANIFEST_CLI_FLEET_ROOT/README.md" ]]; then
        (
            MANIFEST_CLI_PROJECT_ROOT="$MANIFEST_CLI_FLEET_ROOT"
            update_readme_version "$fleet_version" "$timestamp" 2>/dev/null || true
        )
    fi
}

_manifest_docs_fleet_index() {
    local fleet_version="$1"
    local timestamp="$2"
    local fleet_docs_dir="$3"

    local per_service_folder
    per_service_folder=$(get_fleet_config_value "docs_per_service_folder" "$MANIFEST_CLI_FLEET_DEFAULT_DOCS_PER_SERVICE_FOLDER")

    local index_file="$fleet_docs_dir/INDEX.md"
    cat > "$index_file" << EOF
# Fleet Documentation Index

**Fleet:** ${MANIFEST_CLI_FLEET_NAME}
**Version:** ${fleet_version}
**Last Updated:** ${timestamp}

## Services

| Service | Version | Docs |
|---------|---------|------|
EOF

    for service in $MANIFEST_CLI_FLEET_SERVICES; do
        local path excluded version rel_path
        path=$(get_fleet_service_property "$service" "path")
        excluded=$(get_fleet_service_property "$service" "excluded" "false")

        [[ "$excluded" == "true" ]] && continue

        version="unknown"
        if [[ -d "$path" ]] && declare -F _get_repo_version >/dev/null 2>&1; then
            version=$(_get_repo_version "$path" 2>/dev/null || echo "unknown")
        elif [[ -f "$path/VERSION" ]]; then
            version=$(cat "$path/VERSION" 2>/dev/null || echo "unknown")
        fi

        if declare -F _compute_relpath >/dev/null 2>&1; then
            rel_path=$(_compute_relpath "$path/$per_service_folder" "$fleet_docs_dir")
        else
            rel_path="$path/$per_service_folder"
        fi

        echo "| ${service} | v${version} | [docs](${rel_path}/) |" >> "$index_file"
    done

    cat >> "$index_file" << EOF

---
*Generated by Manifest CLI*
EOF

    log_success "Fleet docs index generated: $index_file"
}

_manifest_docs_generate_fleet_root() {
    local fleet_version="$1"
    local timestamp="$2"
    local release_type="${3:-patch}"

    local docs_folder detail_level fleet_docs_dir gen_index gen_readme_version
    docs_folder=$(get_fleet_config_value "docs_fleet_root_folder" "$MANIFEST_CLI_FLEET_DEFAULT_DOCS_FLEET_ROOT_FOLDER")
    detail_level=$(get_fleet_config_value "docs_fleet_root_detail_level" "$MANIFEST_CLI_FLEET_DEFAULT_DOCS_FLEET_ROOT_DETAIL_LEVEL")
    fleet_docs_dir="$MANIFEST_CLI_FLEET_ROOT/$docs_folder"
    mkdir -p "$fleet_docs_dir"

    log_info "Generating fleet-root docs in $fleet_docs_dir (detail_level: $detail_level)..."

    gen_index=$(get_fleet_config_value "docs_gen_index" "$MANIFEST_CLI_FLEET_DEFAULT_DOCS_GEN_INDEX")
    gen_readme_version=$(get_fleet_config_value "docs_gen_readme_version" "$MANIFEST_CLI_FLEET_DEFAULT_DOCS_GEN_README_VERSION")

    if [[ "$detail_level" == "summary" ]]; then
        _manifest_docs_fleet_root_summary "$fleet_version" "$timestamp" "$release_type" \
            "$fleet_docs_dir" "$gen_index" "$gen_readme_version"
    elif [[ "$detail_level" == "index" ]]; then
        [[ "$gen_index" == "true" ]] && _manifest_docs_fleet_index "$fleet_version" "$timestamp" "$fleet_docs_dir"
    else
        log_warning "Unknown fleet docs detail_level: $detail_level, falling back to summary"
        _manifest_docs_fleet_root_summary "$fleet_version" "$timestamp" "$release_type" \
            "$fleet_docs_dir" "$gen_index" "$gen_readme_version"
    fi

    if _manifest_docs_site_enabled; then
        MANIFEST_CLI_PROJECT_ROOT="$MANIFEST_CLI_FLEET_ROOT" _manifest_docs_generate_site \
            "$fleet_version" "$timestamp" "fleet-root" "$MANIFEST_CLI_FLEET_ROOT" "$fleet_docs_dir"
    fi

    log_success "Fleet-root documentation generated in $fleet_docs_dir"
}

# Main document generation function
manifest_docs_generate() {
    local version="$1"
    local timestamp="$2"
    local release_type="${3:-patch}"
    local scope="${4:-repo}"

    if ! _manifest_docs_config_bool "${MANIFEST_CLI_DOCS_GENERATE_ENABLED:-true}" "true"; then
        log_info "Documentation generation disabled by docs.generate.enabled"
        return 0
    fi

    if [[ "$scope" == "fleet-root" ]]; then
        _manifest_docs_generate_fleet_root "$version" "$timestamp" "$release_type"
        return $?
    fi

    log_info "Starting document generation for version $version..."
    
    # Ensure docs directory exists
    mkdir -p "$(get_docs_dir)"
    
    # Create temporary changes file
    local changes_file=$(mktemp "$(manifest_make_scratch_path docs)/tmp.XXXXXXXX")
    
    # Get and analyze changes
    get_git_changes "$version" > "$changes_file"
    analyze_changes "$version" "$changes_file"

    # If a release-notes provider is configured, hand it the analyzed
    # bullets + changed files and let it synthesize the entry body. The
    # helper rewrites changes_file in place on success; on failure it
    # warns and falls back unless docs.release_notes.required is true.
    if ! _manifest_release_notes_run_provider \
        "$version" "$release_type" "$timestamp" "$changes_file"; then
        rm -f "$changes_file"
        log_error "Release-notes provider failure (required=true) — aborting document generation"
        return 1
    fi

    # Prepend a Keep-a-Changelog entry to root CHANGELOG.md for this version.
    if _manifest_docs_config_bool "${MANIFEST_CLI_DOCS_GENERATE_CHANGELOG:-true}" "true"; then
        if ! prepend_root_changelog_entry "$MANIFEST_CLI_PROJECT_ROOT" "$version" "$timestamp" "$release_type" "$changes_file"; then
            log_warning "Root CHANGELOG.md update failed, but continuing..."
        fi
    fi
    if _manifest_docs_config_bool "${MANIFEST_CLI_DOCS_GENERATE_README_VERSION:-true}" "true"; then
        if ! update_readme_version "$version" "$timestamp"; then
            log_warning "README version update failed, but continuing..."
        fi
    fi
    if _manifest_docs_config_bool "${MANIFEST_CLI_DOCS_GENERATE_INDEX:-true}" "true"; then
        if ! generate_docs_index "$version"; then
            log_warning "Documentation index generation failed, but continuing..."
        fi
    fi

    if _manifest_docs_site_enabled; then
        if ! _manifest_docs_generate_site "$version" "$timestamp" "$scope" "$MANIFEST_CLI_PROJECT_ROOT" "$(get_docs_dir)"; then
            rm -f "$changes_file"
            return 1
        fi
    fi

    # Clean up
    rm -f "$changes_file"
    
    log_success "Document generation completed for version $version"
}

# Main function for command-line usage
main() {
    case "${1:-help}" in
        "generate")
            local version="${2:-}"
            local timestamp="${3:-}"
            
            # Get trusted timestamp if not provided
            if [ -z "$timestamp" ]; then
                get_time_timestamp >/dev/null
                timestamp=$(format_timestamp "$MANIFEST_CLI_TIME_TIMESTAMP" '+%Y-%m-%d %H:%M:%S UTC')
            fi
            local release_type="${4:-patch}"
            
            if [[ -z "$version" ]]; then
                show_required_arg_error "Version" "generate <version> [timestamp] [release_type]"
            fi
            
            manifest_docs_generate "$version" "$timestamp" "$release_type"
            ;;
        "analyze")
            local version="${2:-}"
            if [[ -z "$version" ]]; then
                show_required_arg_error "Version" "analyze <version>"
            fi
            
            local changes_file=$(mktemp "$(manifest_make_scratch_path docs)/tmp.XXXXXXXX")
            get_git_changes "$version" > "$changes_file"
            analyze_changes "$version" "$changes_file"
            cat "$changes_file"
            rm -f "$changes_file"
            ;;
        "help"|"-h"|"--help")
            echo "Manifest Documentation Module"
            echo "============================"
            echo ""
            echo "Usage: $0 [command] [options]"
            echo ""
            echo "Commands:"
            echo "  generate <version> [timestamp] [type]  - Generate all documents"
            echo "  analyze <version>                      - Analyze changes only"
            echo "  help                                   - Show this help"
            echo ""
            echo "Release Types:"
            echo "  patch, minor, major"
            echo ""
            echo "Examples:"
            echo "  $0 generate 15.28.0"
            echo "  $0 generate 15.28.0 '2025-01-27 10:00:00 UTC' minor"
            echo "  $0 analyze 15.28.0"
            ;;
        *)
            show_usage_error "$1"
            ;;
    esac
}

# If script is being executed directly
if [[ "${BASH_SOURCE[0]}" == "${0}" ]]; then
    main "$@"
fi
