#!/bin/bash

# Manifest Markdown Templates Module
# Provides consistent, well-formatted markdown generation and templates

# Markdown templates module - uses PROJECT_ROOT from core module

# Markdown formatting functions
markdown_header() {
    local level="$1"
    local title="$2"
    local emoji="$3"
    
    # Ensure proper heading level (1-6)
    if [ "$level" -lt 1 ]; then level=1; fi
    if [ "$level" -gt 6 ]; then level=6; fi
    
    local hashes=$(printf "%*s" "$level" | tr ' ' '#')
    echo "${hashes} ${emoji}${title}"
}

markdown_section() {
    local title="$1"
    local emoji="$2"
    echo ""
    echo "## ${emoji}${title}"
    echo ""
}

markdown_subsection() {
    local title="$1"
    local emoji="$2"
    echo ""
    echo "### ${emoji}${title}"
    echo ""
}

markdown_list_item() {
    local text="$1"
    local emoji="$2"
    echo "- ${emoji}${text}"
}

markdown_code_block() {
    local language="$1"
    local code="$2"
    echo ""
    echo "\`\`\`${language}"
    echo "$code"
    echo "\`\`\`"
    echo ""
}

markdown_inline_code() {
    local code="$1"
    echo "\`${code}\`"
}

markdown_bold() {
    local text="$1"
    echo "**${text}**"
}

markdown_italic() {
    local text="$1"
    echo "*${text}*"
}

markdown_link() {
    local text="$1"
    local url="$2"
    echo "[${text}](${url})"
}

markdown_table_header() {
    local headers=("$@")
    local header_line=""
    local separator_line=""
    
    for header in "${headers[@]}"; do
        header_line="${header_line}| ${header} "
        separator_line="${separator_line}|---"
    done
    
    echo "${header_line}|"
    echo "${separator_line}|"
}

markdown_table_row() {
    local values=("$@")
    local row=""
    
    for value in "${values[@]}"; do
        row="${row}| ${value} "
    done
    
    echo "${row}|"
}

# Template for release notes
generate_release_notes_template() {
    local version="$1"
    local timestamp="$2"
    local release_type="$3"
    local repo_name
    repo_name="$(manifest_repo_display_name "$PROJECT_ROOT")"
    local docs_dir_name
    docs_dir_name="$(basename "$(get_docs_folder "$PROJECT_ROOT")")"
    local archive_dir_name
    archive_dir_name="$(basename "$(get_zarchive_dir)")"

    if manifest_is_canonical_repo "$PROJECT_ROOT"; then
        cat << EOF
# Release v${version}

**Release Date:** ${timestamp}
**Release Type:** ${release_type}

## 🎯 What's New

This release includes various improvements and bug fixes.

## 🔧 Changes

- General improvements and bug fixes
- Enhanced CLI functionality
- Improved error handling

## 🚀 Installation

\`\`\`bash
# Install the CLI
curl -fsSL https://raw.githubusercontent.com/fidenceio/manifest.cli/main/install-cli.sh | bash

# Or clone and install manually
git clone https://github.com/fidenceio/manifest.cli.git
cd manifest.cli
./install-cli.sh
\`\`\`

## 📋 Usage

\`\`\`bash
# Complete workflow
manifest prep patch

# Version bump
manifest prep patch

# Documentation
manifest docs
\`\`\`

## 📚 Documentation

- [User Guide]($(basename "$(get_docs_folder)")/USER_GUIDE.md)
- [Command Reference]($(basename "$(get_docs_folder)")/COMMAND_REFERENCE.md)
- [Examples]($(basename "$(get_docs_folder)")/EXAMPLES.md)

## 🔗 Links

- [GitHub Repository](https://github.com/fidenceio/fidenceio.manifest.cli)
- [Issues](https://github.com/fidenceio/fidenceio.manifest.cli/issues)
- [Discussions](https://github.com/fidenceio/fidenceio.manifest.cli/discussions)

---
*Generated by Manifest CLI v${version}*
EOF
        return 0
    fi

    cat << EOF
# Release v${version}

**Repository:** ${repo_name}
**Release Date:** ${timestamp}
**Release Type:** ${release_type}

## Summary

This release captures the repository changes for v${version}.

## Release Artifacts

- [Detailed changelog](CHANGELOG_v${version}.md)
- [Documentation index](INDEX.md)
- [Archived releases](${archive_dir_name}/)
EOF
}

# Template for changelog
generate_changelog_template() {
    local version="$1"
    local timestamp="$2"
    local release_type="$3"
    local repo_name
    repo_name="$(manifest_repo_display_name "$PROJECT_ROOT")"

    if manifest_is_canonical_repo "$PROJECT_ROOT"; then
        cat << EOF
# Changelog v${version}

**Release Date:** ${timestamp}
**Release Type:** ${release_type}

## 🆕 New Features

- Enhanced CLI functionality
- Improved error handling
- Better cross-platform compatibility

## 🔧 Improvements

- Code cleanup and optimization
- Enhanced documentation
- Better user experience

## 🐛 Bug Fixes

- Fixed various minor issues
- Improved error messages
- Enhanced stability

## 📚 Documentation

- Updated user guide
- Enhanced examples
- Improved command reference

## 🔄 Changes

- Updated dependencies
- Improved performance
- Enhanced security

---
*Generated by Manifest CLI v${version}*
EOF
        return 0
    fi

    cat << EOF
# Changelog v${version}

**Repository:** ${repo_name}
**Release Date:** ${timestamp}
**Release Type:** ${release_type}

## Summary

This document records the detailed changes shipped in v${version}.

## Related Documents

- [Release notes](RELEASE_v${version}.md)
- [Documentation index](INDEX.md)
EOF
}

# Template for README version update
generate_readme_version_section() {
    local version="$1"
    local timestamp="$2"
    local docs_dir_name
    docs_dir_name="$(basename "$(get_docs_folder "$PROJECT_ROOT")")"

    if manifest_is_canonical_repo "$PROJECT_ROOT"; then
    cat << EOF
## 📋 Version Information

| Property | Value |
|----------|-------|
| **Current Version** | \`${version}\` |
| **Release Date** | \`${timestamp}\` |
| **Git Tag** | \`v${version}\` |
| **Branch** | \`main\` |
| **Last Updated** | \`${timestamp}\` |
| **CLI Version** | \`${version}\` |
EOF

        cat << EOF

### 📚 Documentation Files

- **Version Info**: [VERSION](VERSION)
- **CLI Modules**: [modules/](modules/)
- **Install Script**: [install-cli.sh](install-cli.sh)
EOF
        return 0
    fi

    cat << EOF
## Version Information

| Property | Value |
|----------|-------|
| Current Version | \`${version}\` |
| Release Date | \`${timestamp}\` |
| Git Tag | \`v${version}\` |
| Release Notes | [${docs_dir_name}/RELEASE_v${version}.md](${docs_dir_name}/RELEASE_v${version}.md) |
| Changelog | [${docs_dir_name}/CHANGELOG_v${version}.md](${docs_dir_name}/CHANGELOG_v${version}.md) |
| Last Updated | \`${timestamp}\` |
EOF
}

# Template for command help sections
generate_command_help_template() {
    local command="$1"
    local description="$2"
    local emoji="$3"
    local examples="$4"
    
    cat << EOF
## ${emoji} \`${command}\` - ${description}

${description}

### Usage

\`\`\`bash
${examples}
\`\`\`

### Options

- Use \`manifest ${command} --help\` for detailed options
- All commands support \`--verbose\` for detailed output

### Examples

\`\`\`bash
# Basic usage
manifest ${command}

# With options
manifest ${command} --option value
\`\`\`
EOF
}

# Template for configuration sections
generate_config_section_template() {
    local title="$1"
    local description="$2"
    local variables="$3"
    
    cat << EOF
## ${title}

${description}

| Variable | Description | Default |
|----------|-------------|---------|
EOF
    
    # Add variables
    while IFS='|' read -r var desc default; do
        echo "| \`${var}\` | ${desc} | \`${default}\` |"
    done <<< "$variables"
    
    echo ""
    echo "### Example Configuration"
    echo ""
    echo "\`\`\`bash"
    echo "# Add to your .env file"
    while IFS='|' read -r var desc default; do
        echo "${var}=\"${default}\""
    done <<< "$variables"
    echo "\`\`\`"
}

# Template for troubleshooting sections
generate_troubleshooting_template() {
    local issue="$1"
    local symptoms="$2"
    local solutions="$3"
    
    cat << EOF
### ${issue}

**Symptoms:**
${symptoms}

**Solutions:**
${solutions}

**Prevention:**
- Regular maintenance
- Proper configuration
- Following best practices
EOF
}

# Template for workflow examples
generate_workflow_template() {
    local title="$1"
    local description="$2"
    local steps="$3"
    local commands="$4"
    
    cat << EOF
## ${title}

${description}

### Steps

${steps}

### Commands

\`\`\`bash
${commands}
\`\`\`

### What Happens

- Version bump
- Documentation generation
- Git operations
- Remote synchronization
EOF
}

# Main function for command-line usage
main() {
    case "${1:-help}" in
        "release")
            generate_release_notes_template "${2:-}" "${3:-}" "${4:-}"
            ;;
        "changelog")
            generate_changelog_template "${2:-}" "${3:-}" "${4:-}"
            ;;
        "readme")
            generate_readme_version_section "${2:-}" "${3:-}"
            ;;
        "help")
            generate_command_help_template "${2:-}" "${3:-}" "${4:-}" "${5:-}"
            ;;
        "config")
            generate_config_section_template "${2:-}" "${3:-}" "${4:-}"
            ;;
        "troubleshooting")
            generate_troubleshooting_template "${2:-}" "${3:-}" "${4:-}"
            ;;
        "workflow")
            generate_workflow_template "${2:-}" "${3:-}" "${4:-}" "${5:-}"
            ;;
        "help"|"-h"|"--help")
            echo "Manifest Markdown Templates Module"
            echo "=================================="
            echo ""
            echo "Usage: $0 [command] [args...]"
            echo ""
            echo "Commands:"
            echo "  release [version] [timestamp] [type]     - Generate release notes template"
            echo "  changelog [version] [timestamp] [type]   - Generate changelog template"
            echo "  readme [version] [timestamp]             - Generate README version section"
            echo "  help [command] [description] [emoji] [examples] - Generate command help"
            echo "  config [title] [description] [variables] - Generate config section"
            echo "  troubleshooting [issue] [symptoms] [solutions] - Generate troubleshooting"
            echo "  workflow [title] [description] [steps] [commands] - Generate workflow"
            echo "  help                                     - Show this help"
            echo ""
            echo "Examples:"
            echo "  $0 release 15.28.0 '2025-01-27 10:00:00 UTC' minor"
            echo "  $0 changelog 15.28.0 '2025-01-27 10:00:00 UTC' patch"
            echo "  $0 readme 15.28.0 '2025-01-27 10:00:00 UTC'"
            ;;
        *)
            show_usage_error "$1"
            ;;
    esac
}

# If script is being executed directly
if [[ "${BASH_SOURCE[0]}" == "${0}" ]]; then
    main "$@"
fi
