#!/bin/bash

# Manifest Documentation Module
# Orchestrates document generation using atomized modules

# Documentation module - uses PROJECT_ROOT from core module

# Get configurable documentation directory
get_docs_dir() {
    get_docs_folder "$PROJECT_ROOT"
}

# Import required modules
MANIFEST_CLI_SCRIPT_DIR="$(get_script_dir)"
source "$(dirname "$MANIFEST_CLI_SCRIPT_DIR")/git/manifest-git-changes.sh"
source "$(dirname "$MANIFEST_CLI_SCRIPT_DIR")/docs/manifest-markdown-templates.sh"
source "$(dirname "$MANIFEST_CLI_SCRIPT_DIR")/docs/manifest-markdown-validation.sh"

MANIFEST_CLI_README_VERSION_START="<!-- manifest:readme-version:start -->"
MANIFEST_CLI_README_VERSION_END="<!-- manifest:readme-version:end -->"
MANIFEST_CLI_ROOT_CHANGELOG_START="<!-- manifest:root-changelog:start -->"
MANIFEST_CLI_ROOT_CHANGELOG_END="<!-- manifest:root-changelog:end -->"
MANIFEST_CLI_INDEX_METADATA_START="<!-- manifest:index-metadata:start -->"
MANIFEST_CLI_INDEX_METADATA_END="<!-- manifest:index-metadata:end -->"
MANIFEST_CLI_INDEX_CURRENT_RELEASE_START="<!-- manifest:index-current-release:start -->"
MANIFEST_CLI_INDEX_CURRENT_RELEASE_END="<!-- manifest:index-current-release:end -->"

manifest_file_has_managed_block() {
    local file="$1"
    local start_marker="$2"
    local end_marker="$3"

    [[ -f "$file" ]] || return 1
    grep -Fqx "$start_marker" "$file" && grep -Fqx "$end_marker" "$file"
}

manifest_replace_managed_block() {
    local file="$1"
    local start_marker="$2"
    local end_marker="$3"
    local content_file="$4"
    local start_line end_line temp_file

    start_line=$(grep -nFx "$start_marker" "$file" | head -1 | cut -d: -f1)
    end_line=$(grep -nFx "$end_marker" "$file" | head -1 | cut -d: -f1)

    if [[ -z "$start_line" ]] || [[ -z "$end_line" ]] || (( end_line <= start_line )); then
        return 1
    fi

    temp_file=$(mktemp)
    if (( start_line > 1 )); then
        head -n $((start_line - 1)) "$file" > "$temp_file"
    else
        : > "$temp_file"
    fi

    printf '%s\n' "$start_marker" >> "$temp_file"
    cat "$content_file" >> "$temp_file"
    printf '%s\n' "$end_marker" >> "$temp_file"
    tail -n +$((end_line + 1)) "$file" >> "$temp_file"
    mv "$temp_file" "$file"
}

manifest_replace_markdown_section() {
    local file="$1"
    local heading="$2"
    local content_file="$3"
    local start_line end_line temp_file

    start_line=$(grep -nF "$heading" "$file" | head -1 | cut -d: -f1)
    [[ -n "$start_line" ]] || return 1

    end_line=$(tail -n +$((start_line + 1)) "$file" | grep -n "^## " | head -1 | cut -d: -f1)
    if [[ -n "$end_line" ]]; then
        end_line=$((start_line + end_line - 1))
    else
        end_line=$(wc -l < "$file")
    fi

    temp_file=$(mktemp)
    if (( start_line > 1 )); then
        head -n $((start_line - 1)) "$file" > "$temp_file"
    else
        : > "$temp_file"
    fi
    cat "$content_file" >> "$temp_file"
    tail -n +$((end_line + 1)) "$file" >> "$temp_file"
    mv "$temp_file" "$file"
}

manifest_is_legacy_generated_readme() {
    local readme_file="$1"
    [[ -f "$readme_file" ]] || return 1

    if grep -Fq "This project uses [Manifest CLI]" "$readme_file"; then
        return 0
    fi
    if grep -Fq "This repo is versioned and documented by [Manifest CLI]" "$readme_file"; then
        return 0
    fi
    if grep -Fq "| **CLI Version** |" "$readme_file"; then
        return 0
    fi

    return 1
}

manifest_is_legacy_generated_root_changelog() {
    local changelog_file="$1"
    [[ -f "$changelog_file" ]] || return 1
    grep -Fq "Generated by Manifest CLI v" "$changelog_file"
}

manifest_is_legacy_generated_index() {
    local index_file="$1"
    [[ -f "$index_file" ]] || return 1
    grep -Fq "<!-- Manifest CLI v" "$index_file" || grep -Fq "# Manifest CLI Documentation" "$index_file"
}

generate_external_index_metadata_block() {
    local version="$1"
    cat << EOF
**Version:** $version | **Updated:** $(date -u '+%Y-%m-%d')
EOF
}

generate_external_index_current_release_block() {
    local version="$1"

    cat << EOF
| Document | Description |
| -------- | ----------- |
| [CHANGELOG.md](../CHANGELOG.md) | All releases, newest first |
EOF
}

write_external_docs_index() {
    local index_file="$1"
    local version="$2"
    local repo_name
    repo_name="$(manifest_repo_display_name "$PROJECT_ROOT")"
    local metadata_file current_release_file
    metadata_file=$(mktemp)
    current_release_file=$(mktemp)

    generate_external_index_metadata_block "$version" > "$metadata_file"
    generate_external_index_current_release_block "$version" > "$current_release_file"

    cat > "$index_file" << EOF
# ${repo_name} Documentation

${MANIFEST_CLI_INDEX_METADATA_START}
$(cat "$metadata_file")
${MANIFEST_CLI_INDEX_METADATA_END}

## Current Release
${MANIFEST_CLI_INDEX_CURRENT_RELEASE_START}
$(cat "$current_release_file")
${MANIFEST_CLI_INDEX_CURRENT_RELEASE_END}
EOF

    rm -f "$metadata_file" "$current_release_file"
}

# Update README version information
# Preserves user-crafted README content. Only updates inline version strings
# and the version metadata section if one already exists. Never prepends a
# new metadata block to a README that doesn't have one.
update_readme_version() {
    local version="$1"
    local timestamp="$2"

    log_info "Updating README version information..."

    local readme_file="$PROJECT_ROOT/README.md"

    if [[ ! -f "$readme_file" ]]; then
        log_warning "README.md not found, skipping version update"
        return 0
    fi

    if manifest_is_canonical_repo "$PROJECT_ROOT"; then
        local temp_file
        temp_file=$(mktemp)

        if grep -q "## 📋 Version Information" "$readme_file"; then
            # README has a version metadata section — replace it in place
            local version_section
            version_section=$(generate_readme_version_section "$version" "$timestamp")
            local version_section_file
            version_section_file=$(mktemp)
            echo "$version_section" > "$version_section_file"

            local start_line end_line
            start_line=$(grep -n "## 📋 Version Information" "$readme_file" | head -1 | cut -d: -f1)
            end_line=$(tail -n +$((start_line + 1)) "$readme_file" | grep -n "^## " | head -1 | cut -d: -f1)

            if [[ -n "$end_line" ]]; then
                end_line=$((start_line + end_line - 1))
            else
                end_line=$(wc -l < "$readme_file")
            fi

            if [[ "$start_line" -gt 1 ]]; then
                head -n $((start_line - 1)) "$readme_file" > "$temp_file"
            else
                : > "$temp_file"
            fi
            cat "$version_section_file" >> "$temp_file"
            tail -n +$((end_line + 1)) "$readme_file" >> "$temp_file"

            rm -f "$version_section_file"
            mv "$temp_file" "$readme_file"
        else
            rm -f "$temp_file"
            local old_version=""
            if [[ -f "$PROJECT_ROOT/VERSION" ]]; then
                old_version=$(grep -oE '`[0-9]+\.[0-9]+\.[0-9]+`' "$readme_file" | head -1 | tr -d '`')
            fi
            if [[ -n "$old_version" ]] && [[ "$old_version" != "$version" ]]; then
                sed -i'' -e "s|\`${old_version}\`|\`${version}\`|g" "$readme_file"
                rm -f "${readme_file}-e"
                log_debug "Updated inline version references: $old_version -> $version"
            fi
        fi

        log_success "README version information updated"
        return 0
    fi

    local version_section_file
    version_section_file=$(mktemp)
    generate_readme_version_section "$version" "$timestamp" > "$version_section_file"

    if manifest_is_legacy_generated_readme "$readme_file"; then
        create_default_readme "$readme_file"
    fi

    if manifest_file_has_managed_block "$readme_file" "$MANIFEST_CLI_README_VERSION_START" "$MANIFEST_CLI_README_VERSION_END"; then
        manifest_replace_managed_block "$readme_file" "$MANIFEST_CLI_README_VERSION_START" "$MANIFEST_CLI_README_VERSION_END" "$version_section_file"
    else
        log_info "Preserving existing README formatting; no Manifest-managed version block found."
    fi

    rm -f "$version_section_file"

    log_success "README version information updated"
}

# Generate documentation index
# If an INDEX.md already exists, updates version numbers and release note
# links in place, preserving user-crafted structure and formatting.
# Only creates the file from a template when it doesn't exist at all.
generate_docs_index() {
    local version="$1"

    log_info "Generating documentation index..."

    local index_file="$(get_docs_dir)/INDEX.md"

    if manifest_is_canonical_repo "$PROJECT_ROOT"; then
        if [[ -f "$index_file" ]]; then
            local old_version=""
            old_version=$(grep -oE '`[0-9]+\.[0-9]+\.[0-9]+`' "$index_file" | head -1 | tr -d '`')
            if [[ -n "$old_version" ]] && [[ "$old_version" != "$version" ]]; then
                sed -i'' -e "s|\`${old_version}\`|\`${version}\`|g" "$index_file"
            fi

            sed -i'' -e "s|^\*\*Version:\*\* [0-9][0-9.]*|\*\*Version:\*\* $version|" "$index_file"

            local today
            today=$(date -u '+%Y-%m-%d')
            sed -i'' -e "s|^\*\*Updated:\*\* [0-9-]*|\*\*Updated:\*\* $today|" "$index_file"
            sed -i'' -e "s|\*\*Updated:\*\* [0-9-]*|\*\*Updated:\*\* $today|g" "$index_file"
            rm -f "${index_file}-e"

            log_success "Documentation index updated: $index_file"
            return 0
        fi

        cat > "$index_file" << EOF
# Manifest CLI Documentation

**Version:** $version | **Updated:** $(date -u '+%Y-%m-%d')

---

## Getting Started

| Document | Description |
| -------- | ----------- |
| [Installation Guide](INSTALLATION.md) | Setup, upgrade, uninstall, and troubleshooting |
| [User Guide](USER_GUIDE.md) | Workflows, daily commands, and configuration |
| [Examples](EXAMPLES.md) | Real-world workflow recipes |

## Reference

| Document | Description |
| -------- | ----------- |
| [Command Reference](COMMAND_REFERENCE.md) | Every command, flag, and option |
| [YAML config example](../examples/manifest.config.yaml.example) | Full schema with all keys + comments |

## Releases

| Document | Description |
| -------- | ----------- |
| [CHANGELOG.md](../CHANGELOG.md) | All releases, newest first |

---

## Quick Start

\`\`\`bash
# Install
brew tap fidenceio/tap && brew install manifest

# Prepare a release locally
manifest prep repo patch

# Publish a release
manifest ship repo minor

# Get help
manifest --help
\`\`\`

<!-- Manifest CLI v$version -->
EOF

        log_success "Documentation index generated: $index_file"
        return 0
    fi

    if [[ -f "$index_file" ]]; then
        if manifest_is_legacy_generated_index "$index_file"; then
            write_external_docs_index "$index_file" "$version"
        elif manifest_file_has_managed_block "$index_file" "$MANIFEST_CLI_INDEX_METADATA_START" "$MANIFEST_CLI_INDEX_METADATA_END" && manifest_file_has_managed_block "$index_file" "$MANIFEST_CLI_INDEX_CURRENT_RELEASE_START" "$MANIFEST_CLI_INDEX_CURRENT_RELEASE_END"; then
            local metadata_file current_release_file
            metadata_file=$(mktemp)
            current_release_file=$(mktemp)
            generate_external_index_metadata_block "$version" > "$metadata_file"
            generate_external_index_current_release_block "$version" > "$current_release_file"
            manifest_replace_managed_block "$index_file" "$MANIFEST_CLI_INDEX_METADATA_START" "$MANIFEST_CLI_INDEX_METADATA_END" "$metadata_file"
            manifest_replace_managed_block "$index_file" "$MANIFEST_CLI_INDEX_CURRENT_RELEASE_START" "$MANIFEST_CLI_INDEX_CURRENT_RELEASE_END" "$current_release_file"
            rm -f "$metadata_file" "$current_release_file"
        else
            log_info "Preserving existing documentation index formatting; no Manifest-managed blocks found."
            return 0
        fi

        log_success "Documentation index updated: $index_file"
        return 0
    fi

    write_external_docs_index "$index_file" "$version"
    log_success "Documentation index generated: $index_file"
}

# Parse a docs.retain spec into kind and value.
#   "N versions" → kind=versions, value=N
#   "N days"     → kind=days, value=N
#   "off" or ""  → kind=off, value=0
# Returns 0 on success, 1 on malformed input. Output written to the named
# variables in $2 (kind) and $3 (value).
_manifest_parse_retention() {
    local raw="$1"
    local _outkind="$2"
    local _outval="$3"

    raw="$(printf '%s' "$raw" | tr -s '[:space:]' ' ')"
    raw="${raw# }"; raw="${raw% }"

    if [[ -z "$raw" || "$raw" == "off" ]]; then
        printf -v "$_outkind" '%s' "off"
        printf -v "$_outval" '%s' "0"
        return 0
    fi

    local num="${raw%% *}"
    local unit="${raw#* }"
    [[ "$num" =~ ^[0-9]+$ ]] || return 1

    case "$unit" in
        version|versions)
            printf -v "$_outkind" '%s' "versions"
            printf -v "$_outval" '%s' "$num"
            ;;
        day|days)
            printf -v "$_outkind" '%s' "days"
            printf -v "$_outval" '%s' "$num"
            ;;
        *)
            return 1
            ;;
    esac
}

# --- Root CHANGELOG.md prepend ----------------------------------------------
#
# Root CHANGELOG.md is the single source of truth for changelog history.
# Each ship prepends a Keep-a-Changelog block under the `# Changelog`
# header, then enforces docs.retain on the resulting section count.

# Title-case a release type ("patch" → "Patch"). Echoes the input
# unchanged when the type is empty or already capitalized.
_manifest_titlecase_release_type() {
    local t="$1"
    case "$t" in
        patch) printf 'Patch' ;;
        minor) printf 'Minor' ;;
        major) printf 'Major' ;;
        revision) printf 'Revision' ;;
        *) printf '%s' "$t" ;;
    esac
}

# Build a Keep-a-Changelog block from a version, timestamp, release type,
# and an analyzed-changes file (the output of analyze_changes). The body
# is the content following `## Highlights for vX` in the changes file.
_manifest_build_changelog_entry() {
    local version="$1"
    local timestamp="$2"
    local release_type="$3"
    local changes_file="$4"

    local release_date="${timestamp%% *}"
    [[ -n "$release_date" ]] || release_date="$(date -u '+%Y-%m-%d')"

    local rtype
    rtype="$(_manifest_titlecase_release_type "$release_type")"

    local body=""
    if [[ -f "$changes_file" ]]; then
        body="$(awk '
            /^## Highlights for v/ { capture=1; next }
            capture { print }
        ' "$changes_file" | awk '
            { lines[NR]=$0 }
            END {
                start=1
                while (start<=NR && lines[start]=="") start++
                end=NR
                while (end>=start && lines[end]=="") end--
                for (i=start; i<=end; i++) print lines[i]
            }
        ')"
    fi

    printf '## [%s] - %s\n\n' "$version" "$release_date"
    if [[ -n "$body" ]]; then
        [[ -n "$rtype" ]] && printf '**Release Type:** %s\n\n' "$rtype"
        printf '%s\n' "$body"
    else
        if [[ -n "$rtype" ]]; then
            printf '**Release Type:** %s — no user-facing changes.\n' "$rtype"
        else
            printf 'No user-facing changes.\n'
        fi
    fi
}

# Prepend (or replace, on re-ship of the same version) a changelog entry
# at the top of root CHANGELOG.md. Creates the file with a `# Changelog`
# header if it doesn't exist yet, or rewrites a legacy auto-generated
# header. Then enforces docs.retain on section count.
prepend_root_changelog_entry() {
    local project_root="$1"
    local version="$2"
    local timestamp="$3"
    local release_type="$4"
    local changes_file="$5"

    local root_changelog="${project_root}/CHANGELOG.md"
    local entry_file
    entry_file="$(mktemp)"
    _manifest_build_changelog_entry "$version" "$timestamp" "$release_type" "$changes_file" \
        > "$entry_file"

    local existing_body_file
    existing_body_file="$(mktemp)"
    if [[ -f "$root_changelog" ]] && ! manifest_is_legacy_generated_root_changelog "$root_changelog"; then
        # Strip the leading `# Changelog\n\n` header (if present); keep the rest.
        # Also drop any existing `## [X.Y.Z]` section matching the current
        # version, so re-shipping the same version replaces rather than
        # duplicates.
        awk -v ver="$version" '
            BEGIN { skip_header=1; skip_dup=0 }
            skip_header && NR==1 && $0 ~ /^# Changelog[[:space:]]*$/ { next }
            skip_header && NR<=2 && $0 ~ /^[[:space:]]*$/ { next }
            { skip_header=0 }
            $0 ~ "^## \\[" ver "\\] - " { skip_dup=1; next }
            skip_dup && /^## \[/ { skip_dup=0 }
            !skip_dup { print }
        ' "$root_changelog" > "$existing_body_file"
    fi

    {
        printf '# Changelog\n\n'
        cat "$entry_file"
        if [[ -s "$existing_body_file" ]]; then
            # Ensure a blank line separates entries.
            local last_char
            last_char="$(tail -c 1 "$entry_file" 2>/dev/null || true)"
            [[ "$last_char" == $'\n' ]] || printf '\n'
            printf '\n'
            cat "$existing_body_file"
        fi
    } > "$root_changelog"

    rm -f "$entry_file" "$existing_body_file"

    _manifest_prune_root_changelog "$root_changelog" \
        "${MANIFEST_CLI_DOCS_RETAIN:-10 versions}"

    log_success "Root CHANGELOG.md updated"
}

# Apply docs.retain to root CHANGELOG.md. "N versions" keeps the top N
# `## [X.Y.Z]` sections; "N days" keeps sections whose date is within
# the last N days; "off" keeps everything. Malformed specs are ignored
# with a warning (the file is left untouched).
_manifest_prune_root_changelog() {
    local file="$1"
    local raw_spec="$2"

    [[ -f "$file" ]] || return 0

    local kind value
    if ! _manifest_parse_retention "$raw_spec" kind value; then
        log_warning "Invalid docs.retain spec: '${raw_spec}' (root CHANGELOG.md not pruned)"
        return 0
    fi
    [[ "$kind" == "off" ]] && return 0

    # For "days", compute the ISO-8601 cutoff date in shell. ISO-8601 dates
    # sort lexicographically, so awk only needs string comparison.
    local cutoff_date=""
    if [[ "$kind" == "days" ]]; then
        if date -u -v "-${value}d" '+%Y-%m-%d' >/dev/null 2>&1; then
            cutoff_date="$(date -u -v "-${value}d" '+%Y-%m-%d')"
        else
            cutoff_date="$(date -u -d "${value} days ago" '+%Y-%m-%d')"
        fi
    fi

    local tmp
    tmp="$(mktemp)"
    awk -v kind="$kind" -v value="$value" -v cutoff="$cutoff_date" '
        function flush_section(    keep) {
            if (section_index == 0) return
            keep = 1
            if (kind == "versions") {
                if (kept >= value) keep = 0
            } else if (kind == "days") {
                if (section_date < cutoff) keep = 0
            }
            if (keep) {
                printf "%s", section_buf
                kept++
            }
        }
        BEGIN { in_section = 0; kept = 0; section_index = 0; section_buf = ""; section_date = "" }
        /^## \[[0-9]+\.[0-9]+\.[0-9]+\] - [0-9]{4}-[0-9]{2}-[0-9]{2}/ {
            flush_section()
            section_index++
            section_buf = $0 "\n"
            match($0, /[0-9]{4}-[0-9]{2}-[0-9]{2}/)
            section_date = substr($0, RSTART, RLENGTH)
            in_section = 1
            next
        }
        in_section { section_buf = section_buf $0 "\n"; next }
        { print }
        END { flush_section() }
    ' "$file" > "$tmp"

    # Strip trailing blank lines.
    awk 'BEGIN{n=0} {lines[++n]=$0} END{
        while (n>0 && lines[n] ~ /^[[:space:]]*$/) n--
        for (i=1; i<=n; i++) print lines[i]
    }' "$tmp" > "${tmp}.trim"
    mv "${tmp}.trim" "$file"
    rm -f "$tmp"
}

# -----------------------------------------------------------------------------
# Release-notes synthesis hook (provider-agnostic)
# -----------------------------------------------------------------------------
# Manifest owns the prompt template, the request format, and the validation
# rules for the entry body. The provider command is a thin transport: read
# the request file ($1), call any LLM/service, write a markdown bullet list
# to the output file ($2). No provider-specific text leaks into CHANGELOG.md.

# Build the request file the provider receives.
_manifest_release_notes_build_request() {
    local request_file="$1"
    local version="$2"
    local release_type="$3"
    local timestamp="$4"
    local changes_file="$5"
    local project_root="$6"

    local release_date="${timestamp%% *}"
    [[ -n "$release_date" ]] || release_date="$(date -u '+%Y-%m-%d')"

    local project_slug=""
    if [[ -n "${MANIFEST_CLI_PROJECT_NAME:-}" ]]; then
        project_slug="$MANIFEST_CLI_PROJECT_NAME"
    elif declare -F manifest_origin_repo_slug >/dev/null 2>&1; then
        project_slug="$(manifest_origin_repo_slug 2>/dev/null || true)"
    fi

    {
        cat <<'EOF'
# Manifest Release Notes Request

## Instructions

Generate the body of a release-notes section. Output ONLY a markdown bullet
list — lines starting with `- ` — and nothing else.

Do NOT output:
- Headings, subheadings, or section titles.
- A version number, date, or release-type line.
- Preamble, summary paragraphs, closing prose, or framing language.
- References to yourself, the assistant, the LLM, or the provider.

Each bullet should be:
- One sentence in past-tense imperative voice (for example "Added X",
  "Fixed Y", "Replaced Z with W").
- Concise but specific — name what changed and, where useful, why a user
  cares.
- Free of internal jargon or implementation-only detail. Group related
  commits into a single bullet when sensible. Drop trivial bookkeeping.

Hard limit: 15 bullets.

EOF
        printf '## Metadata\n\n'
        printf -- '- version: %s\n' "$version"
        printf -- '- release_type: %s\n' "$release_type"
        printf -- '- date: %s\n' "$release_date"
        [[ -n "$project_slug" ]] && printf -- '- project: %s\n' "$project_slug"

        printf '\n## Commit subjects\n\n'
        awk '
            /^### Changes[[:space:]]*$/ { in_body=1; next }
            in_body && /^[[:space:]]*$/ { next }
            in_body { print }
        ' "$changes_file" 2>/dev/null || true

        printf '\n## Changed files\n\n'
        if declare -F _manifest_doc_review_changed_files >/dev/null 2>&1; then
            _manifest_doc_review_changed_files "$project_root" 2>/dev/null \
                | sed 's/^/- /' || true
        fi
    } > "$request_file"
}

# Sanitize a provider's output. Strips preamble before the first bullet,
# trailing prose after the last bullet, rejects banned LLM-preamble
# phrases, and caps at 15 bullets. On success, prints cleaned content to
# stdout and returns 0. On any rejection, returns non-zero (no stdout).
_manifest_release_notes_validate_output() {
    local raw_file="$1"
    [[ -f "$raw_file" ]] || return 1

    local cleaned
    cleaned="$(awk '
        BEGIN { started=0; ended=0; n=0; last_bullet=0 }
        !started && /^- / { started=1 }
        started && !ended {
            if (/^- /) {
                lines[++n] = $0
                last_bullet = n
            } else if (/^[[:space:]]+/) {
                lines[++n] = $0
            } else if (/^[[:space:]]*$/) {
                lines[++n] = ""
            } else {
                ended = 1
            }
        }
        END {
            if (last_bullet == 0) exit 1
            bullets = 0
            for (i=1; i<=last_bullet; i++) {
                if (lines[i] ~ /^- /) {
                    bullets++
                    if (bullets > 15) exit
                }
                print lines[i]
            }
        }
    ' "$raw_file")" || return 1

    [[ -n "$cleaned" ]] || return 1

    case "$cleaned" in
        *"As an AI"*|*"As a language model"*|*"Sure, here"*|*"Here are the"*|*"I'll generate"*|*"I'd be happy"*)
            return 1
            ;;
    esac

    printf '%s\n' "$cleaned"
}

# Returns 1 if MANIFEST_CLI_RELEASE_NOTES_REQUIRED is truthy (caller
# should abort), 0 otherwise (caller falls back to local generator).
_manifest_release_notes_required_failure() {
    if is_truthy "${MANIFEST_CLI_RELEASE_NOTES_REQUIRED:-false}"; then
        return 1
    fi
    return 0
}

# Run the configured release-notes provider. On success, replaces the
# `### Changes` body in changes_file with the validated provider output.
# On failure, returns 0 to fall through to the local body unless
# MANIFEST_CLI_RELEASE_NOTES_REQUIRED is truthy (then returns 1).
_manifest_release_notes_run_provider() {
    local version="$1"
    local release_type="$2"
    local timestamp="$3"
    local changes_file="$4"
    local project_root="${PROJECT_ROOT:-$(pwd)}"
    local provider="${MANIFEST_CLI_RELEASE_NOTES_PROVIDER:-local}"

    case "$provider" in
        ""|local)
            return 0
            ;;
        command)
            ;;
        *)
            log_warning "Unknown release-notes provider: '$provider' (using local generator)"
            _manifest_release_notes_required_failure || return 1
            return 0
            ;;
    esac

    if [[ -z "${MANIFEST_CLI_RELEASE_NOTES_COMMAND:-}" ]]; then
        log_warning "Release-notes provider 'command' has no MANIFEST_CLI_RELEASE_NOTES_COMMAND (using local generator)"
        _manifest_release_notes_required_failure || return 1
        return 0
    fi

    if [[ ! -x "$MANIFEST_CLI_RELEASE_NOTES_COMMAND" ]]; then
        log_warning "Release-notes provider command is not executable: ${MANIFEST_CLI_RELEASE_NOTES_COMMAND} (using local generator)"
        _manifest_release_notes_required_failure || return 1
        return 0
    fi

    local request_file output_file
    request_file="$(mktemp)"
    output_file="$(mktemp)"
    : > "$output_file"

    _manifest_release_notes_build_request \
        "$request_file" "$version" "$release_type" "$timestamp" \
        "$changes_file" "$project_root"

    log_info "Invoking release-notes provider"
    if ! "$MANIFEST_CLI_RELEASE_NOTES_COMMAND" "$request_file" "$output_file"; then
        log_warning "Release-notes provider exited non-zero (using local generator)"
        rm -f "$request_file" "$output_file"
        _manifest_release_notes_required_failure || return 1
        return 0
    fi

    local validated
    if ! validated="$(_manifest_release_notes_validate_output "$output_file")"; then
        log_warning "Release-notes provider output failed validation (using local generator)"
        rm -f "$request_file" "$output_file"
        _manifest_release_notes_required_failure || return 1
        return 0
    fi

    local new_changes
    new_changes="$(mktemp)"
    {
        printf '## Highlights for v%s\n\n### Changes\n\n' "$version"
        printf '%s\n' "$validated"
    } > "$new_changes"
    mv "$new_changes" "$changes_file"

    rm -f "$request_file" "$output_file"
    log_success "Release-notes provider supplied entry body"
    return 0
}

# Update repository metadata
update_repository_metadata() {
    log_info "Updating repository metadata..."

    # This is a placeholder for repository metadata updates
    # Could include updating GitHub repository description, topics, etc.
    # For now, just log that it's being called
    log_success "Repository metadata update completed"
}

# Main document generation function
generate_documents() {
    local version="$1"
    local timestamp="$2"
    local release_type="${3:-patch}"
    
    log_info "Starting document generation for version $version..."
    
    # Ensure docs directory exists
    mkdir -p "$(get_docs_dir)"
    
    # Create temporary changes file
    local changes_file=$(mktemp)
    
    # Get and analyze changes
    get_git_changes "$version" > "$changes_file"
    analyze_changes "$version" "$changes_file"

    # If a release-notes provider is configured, hand it the analyzed
    # bullets + changed files and let it synthesize the entry body. The
    # helper rewrites changes_file in place on success; on failure it
    # warns and falls back unless docs.release_notes.required is true.
    if ! _manifest_release_notes_run_provider \
        "$version" "$release_type" "$timestamp" "$changes_file"; then
        rm -f "$changes_file"
        log_error "Release-notes provider failure (required=true) — aborting document generation"
        return 1
    fi

    # Prepend a Keep-a-Changelog entry to root CHANGELOG.md for this version.
    if ! prepend_root_changelog_entry "$PROJECT_ROOT" "$version" "$timestamp" "$release_type" "$changes_file"; then
        log_warning "Root CHANGELOG.md update failed, but continuing..."
    fi
    if ! update_readme_version "$version" "$timestamp"; then
        log_warning "README version update failed, but continuing..."
    fi
    if ! generate_docs_index "$version"; then
        log_warning "Documentation index generation failed, but continuing..."
    fi

    # Clean up
    rm -f "$changes_file"
    
    log_success "Document generation completed for version $version"
}

# Main function for command-line usage
main() {
    case "${1:-help}" in
        "generate")
            local version="${2:-}"
            local timestamp="${3:-}"
            
            # Get trusted timestamp if not provided
            if [ -z "$timestamp" ]; then
                get_time_timestamp >/dev/null
                timestamp=$(format_timestamp "$MANIFEST_CLI_TIME_TIMESTAMP" '+%Y-%m-%d %H:%M:%S UTC')
            fi
            local release_type="${4:-patch}"
            
            if [[ -z "$version" ]]; then
                show_required_arg_error "Version" "generate <version> [timestamp] [release_type]"
            fi
            
            generate_documents "$version" "$timestamp" "$release_type"
            ;;
        "analyze")
            local version="${2:-}"
            if [[ -z "$version" ]]; then
                show_required_arg_error "Version" "analyze <version>"
            fi
            
            local changes_file=$(mktemp)
            get_git_changes "$version" > "$changes_file"
            analyze_changes "$version" "$changes_file"
            cat "$changes_file"
            rm -f "$changes_file"
            ;;
        "help"|"-h"|"--help")
            echo "Manifest Documentation Module"
            echo "============================"
            echo ""
            echo "Usage: $0 [command] [options]"
            echo ""
            echo "Commands:"
            echo "  generate <version> [timestamp] [type]  - Generate all documents"
            echo "  analyze <version>                      - Analyze changes only"
            echo "  help                                   - Show this help"
            echo ""
            echo "Release Types:"
            echo "  patch, minor, major"
            echo ""
            echo "Examples:"
            echo "  $0 generate 15.28.0"
            echo "  $0 generate 15.28.0 '2025-01-27 10:00:00 UTC' minor"
            echo "  $0 analyze 15.28.0"
            ;;
        *)
            show_usage_error "$1"
            ;;
    esac
}

# If script is being executed directly
if [[ "${BASH_SOURCE[0]}" == "${0}" ]]; then
    main "$@"
fi
