#!/bin/bash

# Manifest Documentation Module
# Orchestrates document generation using atomized modules

# Documentation module - uses PROJECT_ROOT from core module

# Get configurable documentation directory
get_docs_dir() {
    get_docs_folder "$PROJECT_ROOT"
}

# Import required modules
MANIFEST_CLI_SCRIPT_DIR="$(get_script_dir)"
source "$(dirname "$MANIFEST_CLI_SCRIPT_DIR")/git/manifest-git-changes.sh"
source "$(dirname "$MANIFEST_CLI_SCRIPT_DIR")/docs/manifest-markdown-templates.sh"
source "$(dirname "$MANIFEST_CLI_SCRIPT_DIR")/docs/manifest-markdown-validation.sh"

MANIFEST_README_VERSION_START="<!-- manifest:readme-version:start -->"
MANIFEST_README_VERSION_END="<!-- manifest:readme-version:end -->"
MANIFEST_ROOT_CHANGELOG_START="<!-- manifest:root-changelog:start -->"
MANIFEST_ROOT_CHANGELOG_END="<!-- manifest:root-changelog:end -->"
MANIFEST_INDEX_METADATA_START="<!-- manifest:index-metadata:start -->"
MANIFEST_INDEX_METADATA_END="<!-- manifest:index-metadata:end -->"
MANIFEST_INDEX_CURRENT_RELEASE_START="<!-- manifest:index-current-release:start -->"
MANIFEST_INDEX_CURRENT_RELEASE_END="<!-- manifest:index-current-release:end -->"

manifest_file_has_managed_block() {
    local file="$1"
    local start_marker="$2"
    local end_marker="$3"

    [[ -f "$file" ]] || return 1
    grep -Fqx "$start_marker" "$file" && grep -Fqx "$end_marker" "$file"
}

manifest_replace_managed_block() {
    local file="$1"
    local start_marker="$2"
    local end_marker="$3"
    local content_file="$4"
    local start_line end_line temp_file

    start_line=$(grep -nFx "$start_marker" "$file" | head -1 | cut -d: -f1)
    end_line=$(grep -nFx "$end_marker" "$file" | head -1 | cut -d: -f1)

    if [[ -z "$start_line" ]] || [[ -z "$end_line" ]] || (( end_line <= start_line )); then
        return 1
    fi

    temp_file=$(mktemp)
    if (( start_line > 1 )); then
        head -n $((start_line - 1)) "$file" > "$temp_file"
    else
        : > "$temp_file"
    fi

    printf '%s\n' "$start_marker" >> "$temp_file"
    cat "$content_file" >> "$temp_file"
    printf '%s\n' "$end_marker" >> "$temp_file"
    tail -n +$((end_line + 1)) "$file" >> "$temp_file"
    mv "$temp_file" "$file"
}

manifest_replace_markdown_section() {
    local file="$1"
    local heading="$2"
    local content_file="$3"
    local start_line end_line temp_file

    start_line=$(grep -nF "$heading" "$file" | head -1 | cut -d: -f1)
    [[ -n "$start_line" ]] || return 1

    end_line=$(tail -n +$((start_line + 1)) "$file" | grep -n "^## " | head -1 | cut -d: -f1)
    if [[ -n "$end_line" ]]; then
        end_line=$((start_line + end_line - 1))
    else
        end_line=$(wc -l < "$file")
    fi

    temp_file=$(mktemp)
    if (( start_line > 1 )); then
        head -n $((start_line - 1)) "$file" > "$temp_file"
    else
        : > "$temp_file"
    fi
    cat "$content_file" >> "$temp_file"
    tail -n +$((end_line + 1)) "$file" >> "$temp_file"
    mv "$temp_file" "$file"
}

manifest_is_legacy_generated_readme() {
    local readme_file="$1"
    [[ -f "$readme_file" ]] || return 1

    if grep -Fq "This project uses [Manifest CLI]" "$readme_file"; then
        return 0
    fi
    if grep -Fq "This repo is versioned and documented by [Manifest CLI]" "$readme_file"; then
        return 0
    fi
    if grep -Fq "| **CLI Version** |" "$readme_file"; then
        return 0
    fi

    return 1
}

manifest_is_legacy_generated_root_changelog() {
    local changelog_file="$1"
    [[ -f "$changelog_file" ]] || return 1
    grep -Fq "Generated by Manifest CLI v" "$changelog_file"
}

manifest_is_legacy_generated_index() {
    local index_file="$1"
    [[ -f "$index_file" ]] || return 1
    grep -Fq "<!-- Manifest CLI v" "$index_file" || grep -Fq "# Manifest CLI Documentation" "$index_file"
}

generate_root_changelog_release_block() {
    local version="$1"
    local timestamp="$2"
    local release_date="${timestamp%% *}"
    local docs_dir_name
    docs_dir_name="$(basename "$(get_docs_folder "$PROJECT_ROOT")")"

    cat << EOF
## [${version}] - ${release_date}

See [${docs_dir_name}/CHANGELOG_v${version}.md](${docs_dir_name}/CHANGELOG_v${version}.md) for the detailed changelog and [${docs_dir_name}/RELEASE_v${version}.md](${docs_dir_name}/RELEASE_v${version}.md) for release notes.
EOF
}

generate_external_index_metadata_block() {
    local version="$1"
    cat << EOF
**Version:** $version | **Updated:** $(date -u '+%Y-%m-%d')
EOF
}

generate_external_index_current_release_block() {
    local version="$1"
    local archive_dir_name
    archive_dir_name="$(basename "$(get_zarchive_dir)")"

    cat << EOF
| Document | Description |
| -------- | ----------- |
| [Release Notes v${version}](RELEASE_v${version}.md) | Summary for this release |
| [Changelog v${version}](CHANGELOG_v${version}.md) | Detailed change log |
| [Archived Releases](${archive_dir_name}/) | Previous version documentation |
EOF
}

write_external_docs_index() {
    local index_file="$1"
    local version="$2"
    local repo_name
    repo_name="$(manifest_repo_display_name "$PROJECT_ROOT")"
    local metadata_file current_release_file
    metadata_file=$(mktemp)
    current_release_file=$(mktemp)

    generate_external_index_metadata_block "$version" > "$metadata_file"
    generate_external_index_current_release_block "$version" > "$current_release_file"

    cat > "$index_file" << EOF
# ${repo_name} Documentation

${MANIFEST_INDEX_METADATA_START}
$(cat "$metadata_file")
${MANIFEST_INDEX_METADATA_END}

## Current Release
${MANIFEST_INDEX_CURRENT_RELEASE_START}
$(cat "$current_release_file")
${MANIFEST_INDEX_CURRENT_RELEASE_END}
EOF

    rm -f "$metadata_file" "$current_release_file"
}

# Generate release notes
generate_release_notes() {
    local version="$1"
    local timestamp="$2"
    local release_type="$3"
    local changes_file="$4"
    
    log_info "Generating release notes for v$version..."
    
    local release_file="$(get_docs_dir)/RELEASE_v$version.md"
    
    # Generate template
    local content=$(generate_release_notes_template "$version" "$timestamp" "$release_type")
    
    # Add actual changes if available
    if [[ -f "$changes_file" ]]; then
        local changes=$(cat "$changes_file" | sed 's/\x1b\[[0-9;]*m//g')  # Remove color codes
        # Append changes to the end of the document
        content="${content}

## 🔧 Actual Changes

${changes}"
    fi
    
    # Write the file with proper newline
    echo "$content" > "$release_file"
    echo "" >> "$release_file"
    
    if [[ -f "$release_file" ]]; then
        log_success "Release notes generated: $release_file"
        return 0
    else
        log_error "Failed to generate release notes"
        return 1
    fi
}

# Generate changelog
generate_changelog() {
    local version="$1"
    local timestamp="$2"
    local release_type="$3"
    local changes_file="$4"
    
    log_info "Generating changelog for v$version..."
    
    local changelog_file="$(get_docs_dir)/CHANGELOG_v$version.md"
    
    # Generate template
    local content=$(generate_changelog_template "$version" "$timestamp" "$release_type")
    
    # Add actual changes if available
    if [[ -f "$changes_file" ]]; then
        local changes=$(cat "$changes_file" | sed 's/\x1b\[[0-9;]*m//g')  # Remove color codes
        # Append changes to the end of the document
        content="${content}

## 🔧 Actual Changes

${changes}"
    fi
    
    # Write the file with proper newline
    echo "$content" > "$changelog_file"
    echo "" >> "$changelog_file"
    
    if [[ -f "$changelog_file" ]]; then
        log_success "Changelog generated: $changelog_file"
        return 0
    else
        log_error "Failed to generate changelog"
        return 1
    fi
}

# Update README version information
# Preserves user-crafted README content. Only updates inline version strings
# and the version metadata section if one already exists. Never prepends a
# new metadata block to a README that doesn't have one.
update_readme_version() {
    local version="$1"
    local timestamp="$2"

    log_info "Updating README version information..."

    local readme_file="$PROJECT_ROOT/README.md"

    if [[ ! -f "$readme_file" ]]; then
        log_warning "README.md not found, skipping version update"
        return 0
    fi

    if manifest_is_canonical_repo "$PROJECT_ROOT"; then
        local temp_file
        temp_file=$(mktemp)

        if grep -q "## 📋 Version Information" "$readme_file"; then
            # README has a version metadata section — replace it in place
            local version_section
            version_section=$(generate_readme_version_section "$version" "$timestamp")
            local version_section_file
            version_section_file=$(mktemp)
            echo "$version_section" > "$version_section_file"

            local start_line end_line
            start_line=$(grep -n "## 📋 Version Information" "$readme_file" | head -1 | cut -d: -f1)
            end_line=$(tail -n +$((start_line + 1)) "$readme_file" | grep -n "^## " | head -1 | cut -d: -f1)

            if [[ -n "$end_line" ]]; then
                end_line=$((start_line + end_line - 1))
            else
                end_line=$(wc -l < "$readme_file")
            fi

            if [[ "$start_line" -gt 1 ]]; then
                head -n $((start_line - 1)) "$readme_file" > "$temp_file"
            else
                : > "$temp_file"
            fi
            cat "$version_section_file" >> "$temp_file"
            tail -n +$((end_line + 1)) "$readme_file" >> "$temp_file"

            rm -f "$version_section_file"
            mv "$temp_file" "$readme_file"
        else
            rm -f "$temp_file"
            local old_version=""
            if [[ -f "$PROJECT_ROOT/VERSION" ]]; then
                old_version=$(grep -oE '`[0-9]+\.[0-9]+\.[0-9]+`' "$readme_file" | head -1 | tr -d '`')
            fi
            if [[ -n "$old_version" ]] && [[ "$old_version" != "$version" ]]; then
                sed -i'' -e "s|\`${old_version}\`|\`${version}\`|g" "$readme_file"
                sed -i'' -e "s|RELEASE_v[0-9][0-9.]*\.md|RELEASE_v${version}.md|g" "$readme_file"
                rm -f "${readme_file}-e"
                log_debug "Updated inline version references: $old_version -> $version"
            fi
        fi

        log_success "README version information updated"
        return 0
    fi

    local version_section_file
    version_section_file=$(mktemp)
    generate_readme_version_section "$version" "$timestamp" > "$version_section_file"

    if manifest_is_legacy_generated_readme "$readme_file"; then
        create_default_readme "$readme_file"
    fi

    if manifest_file_has_managed_block "$readme_file" "$MANIFEST_README_VERSION_START" "$MANIFEST_README_VERSION_END"; then
        manifest_replace_managed_block "$readme_file" "$MANIFEST_README_VERSION_START" "$MANIFEST_README_VERSION_END" "$version_section_file"
    else
        log_info "Preserving existing README formatting; no Manifest-managed version block found."
    fi

    rm -f "$version_section_file"

    log_success "README version information updated"
}

# Generate documentation index
# If an INDEX.md already exists, updates version numbers and release note
# links in place, preserving user-crafted structure and formatting.
# Only creates the file from a template when it doesn't exist at all.
generate_docs_index() {
    local version="$1"

    log_info "Generating documentation index..."

    local index_file="$(get_docs_dir)/INDEX.md"

    if manifest_is_canonical_repo "$PROJECT_ROOT"; then
        if [[ -f "$index_file" ]]; then
            local old_version=""
            old_version=$(grep -oE '`[0-9]+\.[0-9]+\.[0-9]+`' "$index_file" | head -1 | tr -d '`')
            if [[ -n "$old_version" ]] && [[ "$old_version" != "$version" ]]; then
                sed -i'' -e "s|\`${old_version}\`|\`${version}\`|g" "$index_file"
            fi

            sed -i'' -e "s|^\*\*Version:\*\* [0-9][0-9.]*|\*\*Version:\*\* $version|" "$index_file"
            sed -i'' -e "s|RELEASE_v[0-9][0-9.]*\.md|RELEASE_v${version}.md|g" "$index_file"
            sed -i'' -e "s|CHANGELOG_v[0-9][0-9.]*\.md|CHANGELOG_v${version}.md|g" "$index_file"
            sed -i'' -e "s|Notes v[0-9][0-9.]*|Notes v${version}|g" "$index_file"
            sed -i'' -e "s|Changelog v[0-9][0-9.]*|Changelog v${version}|g" "$index_file"

            local today
            today=$(date -u '+%Y-%m-%d')
            sed -i'' -e "s|^\*\*Updated:\*\* [0-9-]*|\*\*Updated:\*\* $today|" "$index_file"
            rm -f "${index_file}-e"

            log_success "Documentation index updated: $index_file"
            return 0
        fi

        cat > "$index_file" << EOF
# Manifest CLI Documentation

**Version:** $version | **Updated:** $(date -u '+%Y-%m-%d')

---

## Getting Started

| Document | Description |
| -------- | ----------- |
| [Installation Guide](INSTALLATION.md) | Setup, upgrade, uninstall, and troubleshooting |
| [User Guide](USER_GUIDE.md) | Workflows, daily commands, and configuration |
| [Examples](EXAMPLES.md) | Real-world workflow recipes |

## Reference

| Document | Description |
| -------- | ----------- |
| [Command Reference](COMMAND_REFERENCE.md) | Every command, flag, and option |
| [Git Hooks](GIT_HOOKS.md) | Pre-commit secret protection and hook management |

## Current Release

| Document | Description |
| -------- | ----------- |
| [Release Notes v${version}](RELEASE_v${version}.md) | What's new in this release |
| [Changelog v${version}](CHANGELOG_v${version}.md) | Detailed change log |
| [Archived Releases](zArchive/) | Previous version documentation |

---

## Quick Start

\`\`\`bash
# Install
brew tap fidenceio/tap && brew install manifest

# Prepare a release locally
manifest prep patch

# Publish a release
manifest ship minor

# Get help
manifest --help
\`\`\`

<!-- Manifest CLI v$version -->
EOF

        log_success "Documentation index generated: $index_file"
        return 0
    fi

    if [[ -f "$index_file" ]]; then
        if manifest_is_legacy_generated_index "$index_file"; then
            write_external_docs_index "$index_file" "$version"
        elif manifest_file_has_managed_block "$index_file" "$MANIFEST_INDEX_METADATA_START" "$MANIFEST_INDEX_METADATA_END" && manifest_file_has_managed_block "$index_file" "$MANIFEST_INDEX_CURRENT_RELEASE_START" "$MANIFEST_INDEX_CURRENT_RELEASE_END"; then
            local metadata_file current_release_file
            metadata_file=$(mktemp)
            current_release_file=$(mktemp)
            generate_external_index_metadata_block "$version" > "$metadata_file"
            generate_external_index_current_release_block "$version" > "$current_release_file"
            manifest_replace_managed_block "$index_file" "$MANIFEST_INDEX_METADATA_START" "$MANIFEST_INDEX_METADATA_END" "$metadata_file"
            manifest_replace_managed_block "$index_file" "$MANIFEST_INDEX_CURRENT_RELEASE_START" "$MANIFEST_INDEX_CURRENT_RELEASE_END" "$current_release_file"
            rm -f "$metadata_file" "$current_release_file"
        else
            log_info "Preserving existing documentation index formatting; no Manifest-managed blocks found."
            return 0
        fi

        log_success "Documentation index updated: $index_file"
        return 0
    fi

    write_external_docs_index "$index_file" "$version"
    log_success "Documentation index generated: $index_file"
}

update_root_changelog_for_release() {
    local version="$1"
    local timestamp="$2"
    local root_changelog="$PROJECT_ROOT/CHANGELOG.md"
    local latest_changelog="$(get_docs_folder "$PROJECT_ROOT")/CHANGELOG_v$version.md"

    if manifest_is_canonical_repo "$PROJECT_ROOT"; then
        if [[ -f "$root_changelog" ]] && ! manifest_is_legacy_generated_root_changelog "$root_changelog" && ! manifest_file_has_managed_block "$root_changelog" "$MANIFEST_ROOT_CHANGELOG_START" "$MANIFEST_ROOT_CHANGELOG_END"; then
            log_info "Preserving existing root CHANGELOG.md; no Manifest-managed block found."
            return 0
        fi

        if [[ -f "$latest_changelog" ]]; then
            cp "$latest_changelog" "$root_changelog"
            log_success "Root CHANGELOG.md updated from latest canonical changelog"
        else
            log_warning "Latest changelog not found: $latest_changelog"
        fi
        return 0
    fi

    if [[ ! -f "$root_changelog" ]] || manifest_is_legacy_generated_root_changelog "$root_changelog"; then
        create_default_changelog "$root_changelog"
    fi

    if manifest_file_has_managed_block "$root_changelog" "$MANIFEST_ROOT_CHANGELOG_START" "$MANIFEST_ROOT_CHANGELOG_END"; then
        local changelog_block_file
        changelog_block_file=$(mktemp)
        generate_root_changelog_release_block "$version" "$timestamp" > "$changelog_block_file"
        manifest_replace_managed_block "$root_changelog" "$MANIFEST_ROOT_CHANGELOG_START" "$MANIFEST_ROOT_CHANGELOG_END" "$changelog_block_file"
        rm -f "$changelog_block_file"
        log_success "Root CHANGELOG.md updated"
        return 0
    fi

    log_info "Preserving existing root CHANGELOG.md formatting; no Manifest-managed block found."
}

# Update repository metadata
update_repository_metadata() {
    log_info "Updating repository metadata..."
    
    # This is a placeholder for repository metadata updates
    # Could include updating GitHub repository description, topics, etc.
    # For now, just log that it's being called
    log_success "Repository metadata update completed"
}

# Main document generation function
generate_documents() {
    local version="$1"
    local timestamp="$2"
    local release_type="${3:-patch}"
    
    log_info "Starting document generation for version $version..."
    
    # Ensure docs directory exists
    mkdir -p "$(get_docs_dir)"
    
    # Create temporary changes file
    local changes_file=$(mktemp)
    
    # Get and analyze changes
    get_git_changes "$version" > "$changes_file"
    analyze_changes "$version" "$changes_file"
    
    # Generate documents
    if ! generate_release_notes "$version" "$timestamp" "$release_type" "$changes_file"; then
        log_warning "Release notes generation failed, but continuing..."
    fi
    if ! generate_changelog "$version" "$timestamp" "$release_type" "$changes_file"; then
        log_warning "Changelog generation failed, but continuing..."
    fi
    if ! update_readme_version "$version" "$timestamp"; then
        log_warning "README version update failed, but continuing..."
    fi
    if ! generate_docs_index "$version"; then
        log_warning "Documentation index generation failed, but continuing..."
    fi
    
    # Clean up
    rm -f "$changes_file"
    
    log_success "Document generation completed for version $version"
}

# Main function for command-line usage
main() {
    case "${1:-help}" in
        "generate")
            local version="${2:-}"
            local timestamp="${3:-}"
            
            # Get trusted timestamp if not provided
            if [ -z "$timestamp" ]; then
                get_time_timestamp >/dev/null
                timestamp=$(format_timestamp "$MANIFEST_CLI_TIME_TIMESTAMP" '+%Y-%m-%d %H:%M:%S UTC')
            fi
            local release_type="${4:-patch}"
            
            if [[ -z "$version" ]]; then
                show_required_arg_error "Version" "generate <version> [timestamp] [release_type]"
            fi
            
            generate_documents "$version" "$timestamp" "$release_type"
            ;;
        "analyze")
            local version="${2:-}"
            if [[ -z "$version" ]]; then
                show_required_arg_error "Version" "analyze <version>"
            fi
            
            local changes_file=$(mktemp)
            get_git_changes "$version" > "$changes_file"
            analyze_changes "$version" "$changes_file"
            cat "$changes_file"
            rm -f "$changes_file"
            ;;
        "help"|"-h"|"--help")
            echo "Manifest Documentation Module"
            echo "============================"
            echo ""
            echo "Usage: $0 [command] [options]"
            echo ""
            echo "Commands:"
            echo "  generate <version> [timestamp] [type]  - Generate all documents"
            echo "  analyze <version>                      - Analyze changes only"
            echo "  help                                   - Show this help"
            echo ""
            echo "Release Types:"
            echo "  patch, minor, major"
            echo ""
            echo "Examples:"
            echo "  $0 generate 15.28.0"
            echo "  $0 generate 15.28.0 '2025-01-27 10:00:00 UTC' minor"
            echo "  $0 analyze 15.28.0"
            ;;
        *)
            show_usage_error "$1"
            ;;
    esac
}

# If script is being executed directly
if [[ "${BASH_SOURCE[0]}" == "${0}" ]]; then
    main "$@"
fi
