#!/bin/bash

# Manifest CLI Env Module — `manifest env` (ENV-001, STANDARD.md §2.7)
#
# The spec `env:` block (service.spec.yaml / app.spec.yaml) is the single
# source of truth (D-ENV-2). This module generates the bridge outputs from it:
#
#   .env.example                    stored-name schema template (always)
#   k8s/env/configmap.yaml          non-secret bridge (when k8s/ exists)
#   k8s/env/external-secret.yaml    secret bridge via ESO (when k8s/ exists)
#   Dockerfile marker block         build-time publics ARG→ENV bridge
#
# `env generate` previews by default, applies with -y, and gates drift with
# --check (the run-tests.sh stanza). `env validate` = naming law + drift +
# gitignore hygiene, read-only.

# Guard against multiple sourcing
if [[ -n "${_MANIFEST_CLI_ENV_LOADED:-}" ]]; then
    return 0
fi
_MANIFEST_CLI_ENV_LOADED=1

MANIFEST_CLI_ENV_BRIDGE_BEGIN="# --- manifest env bridge (generated — edit the spec, not this block) ---"
MANIFEST_CLI_ENV_BRIDGE_END="# --- end manifest env bridge ---"

# Does the repo's spec have a non-empty env: block?
_manifest_env_spec_ready() {
    local project_root="$1"
    local spec_file
    spec_file="$(_manifest_env_spec_file "$project_root")"
    [[ -n "$spec_file" ]] || return 1
    command -v yq >/dev/null 2>&1 || return 1
    [[ "$(yq e '.env | length > 0' "$spec_file" 2>/dev/null)" == "true" ]]
}

# Render the generated ConfigMap (non-secret bridge): injected name =
# framework_name (or the FIDENCE name when no bridge is needed), value =
# spec default. Per-{env} values are overlay patches on top of this base.
_manifest_env_render_configmap() {
    local spec_file="$1"
    local project_root="$2"
    local repo_dir
    repo_dir="$(basename "$project_root")"

    printf '# Generated by Manifest CLI from %s `env:` (ENV-001, STANDARD.md §2.7).\n' "$(basename "$spec_file")"
    printf '# Non-secret bridge — inject via `envFrom`. Regenerate: manifest env generate -y\n'
    printf 'apiVersion: v1\n'
    printf 'kind: ConfigMap\n'
    printf 'metadata:\n'
    printf '  name: %s-env\n' "$repo_dir"
    printf 'data:\n'

    local count i name default secret framework_name injected emitted=0
    count="$(yq e '.env | length' "$spec_file" 2>/dev/null)"
    [[ "$count" =~ ^[0-9]+$ ]] || count=0
    for ((i = 0; i < count; i++)); do
        secret="$(yq e ".env[$i].secret // false" "$spec_file" 2>/dev/null)"
        [[ "$secret" == "true" ]] && continue
        name="$(yq e ".env[$i].name // \"\"" "$spec_file" 2>/dev/null)"
        [[ -n "$name" ]] || continue
        default="$(yq e ".env[$i].default // \"\"" "$spec_file" 2>/dev/null)"
        framework_name="$(yq e ".env[$i].framework_name // \"\"" "$spec_file" 2>/dev/null)"
        injected="${framework_name:-$name}"
        printf '  %s: "%s"\n' "$injected" "$default"
        emitted=$((emitted + 1))
    done
    if [[ "$emitted" -eq 0 ]]; then
        printf '  {}\n'
    fi
}

# Render the generated ExternalSecret (secret bridge, D-ENV-3): ESO secretKey
# = injected framework name, remoteRef.property = FIDENCE stored name, path
# secret/{env}/{slug}/{group} (refresh ≤4h per T1-9). `{env}` is patched by
# the per-environment overlay.
_manifest_env_render_external_secret() {
    local spec_file="$1"
    local project_root="$2"
    local repo_dir
    repo_dir="$(basename "$project_root")"

    printf '# Generated by Manifest CLI from %s `env:` (ENV-001, STANDARD.md §2.7).\n' "$(basename "$spec_file")"
    printf '# Secret bridge — OpenBao via ESO; {env} is patched per overlay.\n'
    printf '# Regenerate: manifest env generate -y\n'
    printf 'apiVersion: external-secrets.io/v1\n'
    printf 'kind: ExternalSecret\n'
    printf 'metadata:\n'
    printf '  name: %s-env\n' "$repo_dir"
    printf 'spec:\n'
    printf '  refreshInterval: 1h\n'
    printf '  secretStoreRef:\n'
    printf '    name: openbao-customer\n'
    printf '    kind: ClusterSecretStore\n'
    printf '  target:\n'
    printf '    name: %s-env\n' "$repo_dir"
    printf '    creationPolicy: Owner\n'
    printf '  data:\n'

    local count i name secret framework_name group injected emitted=0
    count="$(yq e '.env | length' "$spec_file" 2>/dev/null)"
    [[ "$count" =~ ^[0-9]+$ ]] || count=0
    for ((i = 0; i < count; i++)); do
        secret="$(yq e ".env[$i].secret // false" "$spec_file" 2>/dev/null)"
        [[ "$secret" == "true" ]] || continue
        name="$(yq e ".env[$i].name // \"\"" "$spec_file" 2>/dev/null)"
        [[ -n "$name" ]] || continue
        framework_name="$(yq e ".env[$i].framework_name // \"\"" "$spec_file" 2>/dev/null)"
        group="$(yq e ".env[$i].group // \"app\"" "$spec_file" 2>/dev/null)"
        injected="${framework_name:-$name}"
        printf '    - secretKey: %s\n' "$injected"
        printf '      remoteRef:\n'
        printf '        key: secret/data/{env}/%s/%s\n' "$repo_dir" "$group"
        printf '        property: %s\n' "$name"
        emitted=$((emitted + 1))
    done
    if [[ "$emitted" -eq 0 ]]; then
        printf '    []\n'
    fi
}

# Render the Dockerfile ARG→ENV bridge block for build-time publics
# (public: true). Empty output = no public vars, no block.
_manifest_env_render_dockerfile_bridge() {
    local spec_file="$1"

    local count i name public framework_name injected lines=""
    count="$(yq e '.env | length' "$spec_file" 2>/dev/null)"
    [[ "$count" =~ ^[0-9]+$ ]] || count=0
    for ((i = 0; i < count; i++)); do
        public="$(yq e ".env[$i].public // false" "$spec_file" 2>/dev/null)"
        [[ "$public" == "true" ]] || continue
        name="$(yq e ".env[$i].name // \"\"" "$spec_file" 2>/dev/null)"
        [[ -n "$name" ]] || continue
        framework_name="$(yq e ".env[$i].framework_name // \"\"" "$spec_file" 2>/dev/null)"
        injected="${framework_name:-$name}"
        lines+="ARG ${name}"$'\n'
        lines+="ENV ${injected}=\${${name}}"$'\n'
    done
    [[ -n "$lines" ]] || return 0

    printf '%s\n' "$MANIFEST_CLI_ENV_BRIDGE_BEGIN"
    printf '%s' "$lines"
    printf '%s\n' "$MANIFEST_CLI_ENV_BRIDGE_END"
}

# Extract the current bridge block from a Dockerfile (empty if none).
_manifest_env_dockerfile_bridge_current() {
    local dockerfile="$1"
    [[ -f "$dockerfile" ]] || return 0
    awk -v begin="$MANIFEST_CLI_ENV_BRIDGE_BEGIN" -v end="$MANIFEST_CLI_ENV_BRIDGE_END" '
        $0 == begin { inside = 1 }
        inside { print }
        $0 == end { inside = 0 }
    ' "$dockerfile"
}

# Replace (or append) the bridge block in a Dockerfile.
_manifest_env_dockerfile_bridge_apply() {
    local dockerfile="$1"
    local block="$2"
    local tmp
    tmp="$(mktemp)"

    if grep -qF "$MANIFEST_CLI_ENV_BRIDGE_BEGIN" "$dockerfile" 2>/dev/null; then
        awk -v begin="$MANIFEST_CLI_ENV_BRIDGE_BEGIN" -v end="$MANIFEST_CLI_ENV_BRIDGE_END" -v block="$block" '
            $0 == begin { inside = 1; print block; next }
            $0 == end { inside = 0; next }
            !inside { print }
        ' "$dockerfile" > "$tmp" || { rm -f "$tmp"; return 1; }
    else
        cat "$dockerfile" > "$tmp" || { rm -f "$tmp"; return 1; }
        printf '\n%s\n' "$block" >> "$tmp"
    fi
    mv "$tmp" "$dockerfile"
}

# One artifact's disposition for generate/preview/check.
#   states: create | update | current
_manifest_env_artifact_state() {
    local target="$1"
    local rendered="$2"
    if [[ ! -f "$target" ]]; then
        printf 'create'
    elif [[ "$(cat "$target")" == "$rendered" ]]; then
        printf 'current'
    else
        printf 'update'
    fi
}

# manifest env generate [--check] [--dry-run] [-y|--yes]
manifest_env_generate() {
    local execution_mode="preview"
    local check_only=false
    local _local_only=false
    local remaining_args=()
    if ! manifest_execution_parse execution_mode _local_only remaining_args "$@"; then
        return 1
    fi
    set -- "${remaining_args[@]}"
    while [[ $# -gt 0 ]]; do
        case "$1" in
            --check) check_only=true ;;
            -h|--help)
                _render_help \
                    "manifest env generate [--check] [--dry-run] [-y|--yes]" \
                    "Generate env bridge artifacts from the spec env: block (ENV-001)." \
                    "Options" "  --dry-run    Explicit preview; no writes (default)
  --check      Drift gate: exit 1 if any generated artifact is stale
  -y, --yes    Write the artifacts" \
                    "Artifacts" "  .env.example                  stored-name schema template
  k8s/env/configmap.yaml        non-secret bridge (when k8s/ exists)
  k8s/env/external-secret.yaml  secret bridge via ESO (when k8s/ exists)
  Dockerfile bridge block       build-time publics ARG→ENV (when present)"
                return 0
                ;;
            *)
                _render_help_error "Unknown option: $1" "manifest env generate [--check] [--dry-run] [-y|--yes]"
                return 1
                ;;
        esac
        shift
    done

    local project_root="${MANIFEST_CLI_PROJECT_ROOT:-$(pwd)}"
    local spec_file
    spec_file="$(_manifest_env_spec_file "$project_root")"

    if ! _manifest_env_spec_ready "$project_root"; then
        echo "No spec env: block found (service.spec.yaml / app.spec.yaml)."
        echo "Declare the repo's environment schema there first — it is the source"
        echo "of truth (STANDARD.md §2.7 D-ENV-2). Scaffold a starter with: manifest init repo -y"
        # Nothing to generate is not drift.
        return 0
    fi

    local apply=false
    [[ "$execution_mode" == "apply" && "$check_only" != "true" ]] && apply=true

    # ---- Render everything first (read-only) --------------------------------
    local example_rendered configmap_rendered external_rendered bridge_rendered
    example_rendered="$(_manifest_env_render_example "$spec_file" "$project_root")"
    configmap_rendered="$(_manifest_env_render_configmap "$spec_file" "$project_root")"
    external_rendered="$(_manifest_env_render_external_secret "$spec_file" "$project_root")"
    bridge_rendered="$(_manifest_env_render_dockerfile_bridge "$spec_file")"

    local -a plan_names=() plan_states=()
    plan_names+=(".env.example")
    plan_states+=("$(_manifest_env_artifact_state "$project_root/.env.example" "$example_rendered")")

    local emit_k8s=false
    if [[ -d "$project_root/k8s" ]]; then
        emit_k8s=true
        plan_names+=("k8s/env/configmap.yaml")
        plan_states+=("$(_manifest_env_artifact_state "$project_root/k8s/env/configmap.yaml" "$configmap_rendered")")
        plan_names+=("k8s/env/external-secret.yaml")
        plan_states+=("$(_manifest_env_artifact_state "$project_root/k8s/env/external-secret.yaml" "$external_rendered")")
    fi

    local emit_bridge=false
    if [[ -n "$bridge_rendered" && -f "$project_root/Dockerfile" ]]; then
        emit_bridge=true
        plan_names+=("Dockerfile (bridge block)")
        if [[ "$(_manifest_env_dockerfile_bridge_current "$project_root/Dockerfile")" == "$bridge_rendered" ]]; then
            plan_states+=("current")
        elif grep -qF "$MANIFEST_CLI_ENV_BRIDGE_BEGIN" "$project_root/Dockerfile" 2>/dev/null; then
            plan_states+=("update")
        else
            plan_states+=("create")
        fi
    fi

    # ---- Report the plan -----------------------------------------------------
    echo ""
    if [[ "$check_only" == "true" ]]; then
        echo "Env drift check — $project_root"
    elif [[ "$apply" == "true" ]]; then
        echo "Generating env artifacts: $project_root"
    else
        echo "Dry run — manifest env generate: $project_root"
    fi
    echo ""

    local i drift=0
    for i in "${!plan_names[@]}"; do
        case "${plan_states[$i]}" in
            current) echo "  up-to-date:   ${plan_names[$i]}" ;;
            create)  echo "  would create: ${plan_names[$i]}"; drift=$((drift + 1)) ;;
            update)  echo "  would update: ${plan_names[$i]}"; drift=$((drift + 1)) ;;
        esac
    done
    echo ""

    if [[ "$check_only" == "true" ]]; then
        if [[ "$drift" -gt 0 ]]; then
            echo "env drift: $drift artifact(s) stale — run: manifest env generate -y"
            return 1
        fi
        echo "env drift: clean"
        return 0
    fi

    if [[ "$apply" != "true" ]]; then
        manifest_execution_footer "manifest env generate -y"
        echo ""
        return 0
    fi

    # ---- Apply ---------------------------------------------------------------
    printf '%s\n' "$example_rendered" > "$project_root/.env.example"
    echo "  wrote: .env.example"
    if [[ "$emit_k8s" == "true" ]]; then
        mkdir -p "$project_root/k8s/env"
        printf '%s\n' "$configmap_rendered" > "$project_root/k8s/env/configmap.yaml"
        echo "  wrote: k8s/env/configmap.yaml"
        printf '%s\n' "$external_rendered" > "$project_root/k8s/env/external-secret.yaml"
        echo "  wrote: k8s/env/external-secret.yaml"
    fi
    if [[ "$emit_bridge" == "true" ]]; then
        if _manifest_env_dockerfile_bridge_apply "$project_root/Dockerfile" "$bridge_rendered"; then
            echo "  wrote: Dockerfile bridge block"
        else
            log_warning "Could not update Dockerfile bridge block"
        fi
    fi
    echo ""
    echo "Env artifacts generated."
    return 0
}

# manifest env validate — read-only: naming law + drift + gitignore hygiene.
manifest_env_validate() {
    if [[ "${1:-}" == "-h" || "${1:-}" == "--help" || "${1:-}" == "help" ]]; then
        _render_help \
            "manifest env validate" \
            "Validate env hygiene: naming law, generated-artifact drift, gitignore." \
            "Checks" "  naming     stored names are FIDENCE_-prefixed or allowlisted (§2.7.1)
  drift      .env.example and k8s/env/* match the spec env: block
  gitignore  .env value files are ignored; only example/template tracked"
        return 0
    fi

    local project_root="${MANIFEST_CLI_PROJECT_ROOT:-$(pwd)}"
    local failures=0

    echo ""
    echo "Env validation — $project_root"
    echo ""

    echo "  naming law (ENV-001, enforcement: ${MANIFEST_CLI_ENV_NAMING_ENFORCEMENT:-warn}):"
    if check_env_naming "$project_root"; then
        echo "      ✅ stored names conform"
    else
        if [[ "${MANIFEST_CLI_ENV_NAMING_ENFORCEMENT:-warn}" == "strict" ]]; then
            failures=$((failures + 1))
            echo "      ❌ violations (strict)"
        else
            echo "      ⚠️  violations (warn — strict at 57.0.0)"
        fi
    fi

    echo "  generated-artifact drift:"
    if _manifest_env_spec_ready "$project_root"; then
        if manifest_env_generate --check >/dev/null 2>&1; then
            echo "      ✅ artifacts match the spec env: block"
        else
            echo "      ❌ stale artifacts — run: manifest env generate -y"
            failures=$((failures + 1))
        fi
    else
        echo "      ℹ️  no spec env: block — nothing generated yet"
    fi

    echo "  gitignore hygiene:"
    if git -C "$project_root" rev-parse --git-dir >/dev/null 2>&1; then
        if check_environment_file_security "$project_root" >/dev/null; then
            echo "      ✅ env value files are git-ignored"
        else
            echo "      ❌ env value files exist that are NOT git-ignored"
            failures=$((failures + 1))
        fi
    else
        echo "      ℹ️  not a git repository — skipped"
    fi

    echo ""
    if [[ "$failures" -gt 0 ]]; then
        echo "env validate: FAIL ($failures check(s))"
        return 1
    fi
    echo "env validate: PASS"
    return 0
}

# Dispatch for `manifest env <generate|validate>`
manifest_env_dispatch() {
    case "${1:-}" in
        generate)
            shift || true
            manifest_env_generate "$@"
            ;;
        validate)
            shift || true
            manifest_env_validate "$@"
            ;;
        help|-h|--help|"")
            _render_help \
                "manifest env <generate|validate>" \
                "Manage env schema artifacts (ENV-001, STANDARD.md §2.7)." \
                "Subcommands" "  generate   Generate .env.example + k8s/Dockerfile bridges from the spec env: block
  validate   Naming law + drift + gitignore hygiene (read-only)"
            [[ -z "${1:-}" ]] && return 1
            return 0
            ;;
        *)
            _render_help_error "Unknown env subcommand: $1" "manifest env <generate|validate>"
            return 1
            ;;
    esac
}
